# 必要ライブラリの読み込み

In [11]:
#ライブラリ読み込み
import lightgbm as lgb
import numpy as np
import sklearn.datasets
import sklearn.metrics
from sklearn.model_selection import train_test_split

import optuna

pd.set_option('display.max_columns',200)
pd.set_option('display.max_rows',200)

# 必要データの読み込み

In [9]:
#データ読み込み

#データ定義
train_input= pd.read_csv('train_0806best.csv')
test_input= pd.read_csv('test_0806best.csv')

In [16]:
category_columns = ['city1',
 'city2',
 'city3',
 '階数',
 '部屋数',
 'jukyo',
 'yoto1',
 'yoto2',
 'josui',
 'gesui',
 'gas',
 'usui',
 'road1_hk',
 'road1_sb',
 'road2_hk',
 'road2_sb',
 'road3_hk',
 'road3_sb',
 'road4_hk',
 'road4_sb',
 'hw_status',
 'toshikuiki1',
 'toshikuiki2',
 'kodochiku',
 'bokachiiki',
 'hokakisei1',
 'hokakisei2',
 'hokakisei3',
 'hokakisei4',
 'kinshijiko',
 'rosen_nm1',
 'eki_nm1',
 'bas_toho1',
 'bastei_nm1',
 'rosen_nm2',
 'eki_nm2',
 'bas_toho2',
 'bastei_nm2',
 'levelplan',
 'road_st',
 'setsudo_hi',
 'setsudo_kj',
 'jigata',
 'hiatari',
 'kobetsu1',
 'kobetsu2',
 'kobetsu3',
 'kobetsu4']

In [18]:
#LightGBMでのカテゴリ扱いをする変数を指定
for column in category_columns:
    train_input[column] = train_input[column].astype('category')
    test_input[column] = test_input[column].astype('category')

In [32]:
y_true = np.array([3, -0.5, 2, 7])
y_pred = np.array( [2.5, 0.0, 2, 8])

In [34]:
np.mean((y_pred  - y_true )/y_true )

-0.255952380952381

In [38]:
y_pred.shape

(4,)

In [28]:
(y_pred - y_true)/y_true 

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [51]:
import lightgbm as lgb
import numpy as np
import sklearn.datasets
import sklearn.metrics
from sklearn.model_selection import train_test_split

import optuna


def objective(trial):
    data = train_input.drop(['id','pj_no','keiyaku_pr'],axis = 1)
    target = train_input[['keiyaku_pr']]
    train_x, test_x, train_y, test_y = train_test_split(data, target, test_size=0.2)
    dtrain = lgb.Dataset(train_x, label=train_y)

    param = {
            'task' : 'train',
            'boosting_type' : 'dart',
            'objective' : 'regression',
            'metric' : {'mape'},
            'num_leaves' : trial.suggest_int('num_leaves', 10, 100),
            'learning_rate' : trial.suggest_loguniform('learning_rate', 1e-8, 1.0),
            'n_estimators' : 1000,
            'feature_fraction' : 0.5,
            'bagging_fraction' : 0.8,
            'bagging_freq': 5,
            'verbose' : 0,
            'drop_rate' : trial.suggest_loguniform('drop_rate', 1e-8, 1.0),
            'skip_drop' : trial.suggest_loguniform('skip_drop', 1e-8, 1.0)
    }

    gbm = lgb.train(param, dtrain)
    preds = gbm.predict(test_x)
    print(preds.shape)
    print(test_y['keiyaku_pr'].values)
#     pred_labels = np.rint(preds)
    test_y = test_y['keiyaku_pr'].values
    
#     mae = sklearn.metrics.mean_absolute_error(test_y,preds)
#     return mae
    
    mape = np.mean(abs(preds  - test_y)/test_y ) * 100
    
    print('hello')
    return mape


if __name__ == '__main__':
    study = optuna.create_study(direction='minimize')
    study.optimize(objective, n_trials=100)

    print('Number of finished trials: {}'.format(len(study.trials)))

    print('Best trial:')
    trial = study.best_trial

    print('  Value: {}'.format(trial.value))

    print('  Params: ')
    for key, value in trial.params.items():
        print('    {}: {}'.format(key, value))

/opt/conda/lib/python3.7/site-packages/lightgbm/engine.py:118: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


(1292,)
[27800000 30000000 29800000 ... 30800000 27800000 32000000]
hello


[I 2019-08-06 15:06:22,887] Finished trial#0 resulted in value: 7.016202808403676. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[43000000 21496297 16800000 ... 17900000 29300000 31800000]
hello


[I 2019-08-06 15:06:35,505] Finished trial#1 resulted in value: 9.38825949836608. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[39800000 34500000 31000000 ... 21000000 32500000 20900000]
hello


[I 2019-08-06 15:06:39,430] Finished trial#2 resulted in value: 7.648905573225822. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[30990000 33800000 22300000 ... 26800000 16200000 26000000]
hello


[I 2019-08-06 15:06:49,305] Finished trial#3 resulted in value: 20.82119035616497. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[22000000 31000000 26000000 ... 43900000 31900000 25500000]
hello


[I 2019-08-06 15:06:53,922] Finished trial#4 resulted in value: 20.72281426881475. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[27000000 22300000 21300000 ... 29800000 27800000 20100000]
hello


[I 2019-08-06 15:07:05,815] Finished trial#5 resulted in value: 7.208069397591498. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[20900000 30800000 31900000 ... 26800000 32900000 21900000]
hello


[I 2019-08-06 15:07:13,917] Finished trial#6 resulted in value: 93.07851610258446. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[30800000 25300000 30319600 ... 36800000 23800000 33800000]
hello


[I 2019-08-06 15:07:22,764] Finished trial#7 resulted in value: 7.428276540098698. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[27800000 31800000 28800000 ... 27800000 33000000 38800000]
hello


[I 2019-08-06 15:07:29,642] Finished trial#8 resulted in value: 25.406153980105994. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[18500000 26500000 31500000 ... 32800000 23800000 20800000]
hello


[I 2019-08-06 15:07:43,421] Finished trial#9 resulted in value: 86.27700065839143. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[22800000 37900000 45900000 ... 42500000 31000000 28300000]
hello


[I 2019-08-06 15:08:15,422] Finished trial#10 resulted in value: 99.89081231134365. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[25900000 19250000 31800000 ... 17900000 18500000 29880000]
hello


[I 2019-08-06 15:09:06,659] Finished trial#11 resulted in value: 94.14717803680584. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[31400000 20300000 22990000 ... 21600000 28000000 20000000]
hello


[I 2019-08-06 15:09:13,773] Finished trial#12 resulted in value: 7.570391929940963. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[21800000 32000000 23000000 ... 37900000 36800000 25800000]
hello


[I 2019-08-06 15:09:23,547] Finished trial#13 resulted in value: 15.96724598615465. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[28000000 20000000 24300000 ... 24180000 32000000 29500000]
hello


[I 2019-08-06 15:09:39,182] Finished trial#14 resulted in value: 97.10484885335924. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[19990000 12400000 24500000 ... 21500000 26800000 29300000]
hello


[I 2019-08-06 15:09:51,958] Finished trial#15 resulted in value: 16.603533841774002. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[28300000 18300000 25800000 ... 22800000 22990000 32980000]
hello


[I 2019-08-06 15:10:02,615] Finished trial#16 resulted in value: 46.31186453064455. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[30000000 23800000 15800000 ... 14000000 30000000 16000000]
hello


[I 2019-08-06 15:10:13,833] Finished trial#17 resulted in value: 7.725161393778787. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[20800000 26800000 27000000 ... 32800000 33800000 31000000]
hello


[I 2019-08-06 15:10:26,768] Finished trial#18 resulted in value: 7.241937064645388. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[20800000 26800000 33800000 ... 27000000 15800000 33900000]
hello


[I 2019-08-06 15:10:37,087] Finished trial#19 resulted in value: 7.352094783251584. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[26318720 19500000 44980000 ... 28000000 18900000 25900000]
hello


[I 2019-08-06 15:11:06,964] Finished trial#20 resulted in value: 28.91429970460791. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[29000000 25300000 36000000 ... 41980000 23800000 20800000]
hello


[I 2019-08-06 15:11:15,887] Finished trial#21 resulted in value: 7.700233645393424. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[41300000 19452312 29300000 ... 34900000 20900000 32000000]
hello


[I 2019-08-06 15:11:28,079] Finished trial#22 resulted in value: 10.58666598416634. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[19800000 22400000 23000000 ... 25000000 20000000 33000000]
hello


[I 2019-08-06 15:11:36,972] Finished trial#23 resulted in value: 20.12211166325569. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[28800000 22800000 21500000 ... 34800000 17000000 25800000]
hello


[I 2019-08-06 15:11:48,047] Finished trial#24 resulted in value: 7.345192732978184. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[37300000 14500000 39980000 ... 35700000 40900000 28000000]
hello


[I 2019-08-06 15:11:59,406] Finished trial#25 resulted in value: 7.808315357405557. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[15000000 26500000 32000000 ... 18300000 24800000 25800000]
hello


[I 2019-08-06 15:12:16,120] Finished trial#26 resulted in value: 9.205101448019883. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[31000000 27300000 21200000 ... 23800000 35300000 29800000]
hello


[I 2019-08-06 15:12:26,868] Finished trial#27 resulted in value: 18.488302534234986. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[35980000 37800000 21300000 ... 26900000 27800000 23900000]
hello


[I 2019-08-06 15:13:15,253] Finished trial#28 resulted in value: 7.705093834100324. Current best value is 7.016202808403676 with parameters: {'num_leaves': 46, 'learning_rate': 0.06510192767154657, 'drop_rate': 0.00014132265634717668, 'skip_drop': 0.2843873897773534}.


(1292,)
[26900000 26000000 29800000 ... 29800000 31800000 27000000]
hello


[I 2019-08-06 15:13:21,801] Finished trial#29 resulted in value: 6.794033244831953. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[24550000 30800000 32800000 ... 26800000 25900000 41000000]
hello


[I 2019-08-06 15:13:28,294] Finished trial#30 resulted in value: 7.255712855986572. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[40500000 18800000 24900000 ... 20400000 22800000 52800000]
hello


[I 2019-08-06 15:13:36,891] Finished trial#31 resulted in value: 21.588549266918232. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[27800000 23900000 26800000 ... 17000000 22800000 35000000]
hello


[I 2019-08-06 15:13:41,424] Finished trial#32 resulted in value: 7.947201883834704. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[27000000 22200000 30300000 ... 37000000 21800000 22800000]
hello


[I 2019-08-06 15:13:47,856] Finished trial#33 resulted in value: 20.422049440724667. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[19800000 41500000 30000000 ... 23000000 16800000 30300000]
hello


[I 2019-08-06 15:13:52,742] Finished trial#34 resulted in value: 17.979189543660873. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[33800000 28300000 36500000 ... 30800000 24800000 23000000]
hello


[I 2019-08-06 15:14:00,298] Finished trial#35 resulted in value: 8.335027154698748. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[23300000 25300000 29000000 ... 27800000 24300000 21300000]
hello


[I 2019-08-06 15:14:03,510] Finished trial#36 resulted in value: 7.277984343124485. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[23800000 29800000 28400000 ... 30000000 30900000 29300000]
hello


[I 2019-08-06 15:14:10,577] Finished trial#37 resulted in value: 7.63772869451554. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[10000000 27900000 34800000 ... 37000000 30004445 24000000]
hello


[I 2019-08-06 15:14:20,511] Finished trial#38 resulted in value: 68.02326710677491. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[22500000 28800000 26800000 ... 22900000 25000000 23800000]
hello


[I 2019-08-06 15:14:37,212] Finished trial#39 resulted in value: 28.80047146205732. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[33500000 39800000 29000000 ... 28900000 29800000 28800000]
hello


[I 2019-08-06 15:14:45,084] Finished trial#40 resulted in value: 19.213637743908503. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[53300000 26800000 23800000 ... 17300000 17000000 32800000]
hello


[I 2019-08-06 15:14:49,627] Finished trial#41 resulted in value: 12.635455598013948. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[27800000 24800000 34800000 ... 26100000 28800000 44800000]
hello


[I 2019-08-06 15:14:58,822] Finished trial#42 resulted in value: 89.195084174846. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[26900000 26000000 24800000 ... 29980000 26800000 18900000]
hello


[I 2019-08-06 15:15:04,501] Finished trial#43 resulted in value: 20.464305154780213. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[27800000 26000000 30000000 ... 31800000 14800000 17000000]
hello


[I 2019-08-06 15:15:28,765] Finished trial#44 resulted in value: 85.00789887072168. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[37212000 23800000 24800000 ... 24000000 27300000 31500000]
hello


[I 2019-08-06 15:15:34,683] Finished trial#45 resulted in value: 7.3196880340728825. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[37000000 27800000 26557780 ... 30300000 31000000 27300000]
hello


[I 2019-08-06 15:15:45,134] Finished trial#46 resulted in value: 74.65790751805821. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[23500000 27000000 22500000 ... 19800000 25500000 33800000]
hello


[I 2019-08-06 15:15:52,315] Finished trial#47 resulted in value: 45.928155918560954. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[38300000 25000000 31800000 ... 19000000 40000000 27800000]
hello


[I 2019-08-06 15:16:04,029] Finished trial#48 resulted in value: 8.104223691495037. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[26000000 17000000 33800000 ... 36800000 26800000 36800000]
hello


[I 2019-08-06 15:16:13,968] Finished trial#49 resulted in value: 47.14539704332062. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[23000000 28500000 23800000 ... 18800000 22500000 35800000]
hello


[I 2019-08-06 15:16:35,954] Finished trial#50 resulted in value: 85.66634811992006. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[18800000 15800000 41500000 ... 35000000 27000000 21300000]
hello


[I 2019-08-06 15:16:48,286] Finished trial#51 resulted in value: 7.317217816082076. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[39300000 23000000 37800000 ... 29300000 26690000 31500000]
hello


[I 2019-08-06 15:16:57,632] Finished trial#52 resulted in value: 25.04376447409282. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[25000000 19000000 21800000 ... 31600000 30500000 19800000]
hello


[I 2019-08-06 15:17:04,526] Finished trial#53 resulted in value: 14.314341984816359. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[20000000 20000000 29000000 ... 29900000 29800000 29000000]
hello


[I 2019-08-06 15:17:34,721] Finished trial#54 resulted in value: 7.690677258792639. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[23800000 30800000 30000000 ... 23800000 31000000 28800000]
hello


[I 2019-08-06 15:17:39,179] Finished trial#55 resulted in value: 20.560332265188265. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[45000000 28300000 28500000 ... 23400000 52000000 22000000]
hello


[I 2019-08-06 15:17:46,165] Finished trial#56 resulted in value: 7.170954977410203. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[21500000 16000000 36000000 ... 19800000 26000000 30980000]
hello


[I 2019-08-06 15:17:56,414] Finished trial#57 resulted in value: 31.903604043995276. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[29800000 35900000 23000000 ... 21600000 45800000 22000000]
hello


[I 2019-08-06 15:18:04,895] Finished trial#58 resulted in value: 21.075596956718393. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[28800000 25800000 27000000 ... 15900000 27800000 33800000]
hello


[I 2019-08-06 15:18:11,146] Finished trial#59 resulted in value: 20.337908165510072. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[33800000 22800000 33900000 ... 32380000 17500000 23500000]
hello


[I 2019-08-06 15:18:20,862] Finished trial#60 resulted in value: 23.901619615377683. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[21800000 30800000 34400000 ... 29500000 35300000 31000000]
hello


[I 2019-08-06 15:18:25,904] Finished trial#61 resulted in value: 8.51175478458999. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[18800000 29800000 24800000 ... 26000000 35800000 26000000]
hello


[I 2019-08-06 15:18:33,791] Finished trial#62 resulted in value: 47.83246818602739. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[25300000 31000000 35800000 ... 24000000 17300000 30800000]
hello


[I 2019-08-06 15:18:39,358] Finished trial#63 resulted in value: 21.333503470210534. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[28800000 33000000 19800000 ... 26400000 25300000 23300000]
hello


[I 2019-08-06 15:18:46,543] Finished trial#64 resulted in value: 57.81250135234946. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[34000000 27000000 20400000 ... 23000000 23100000 22000000]
hello


[I 2019-08-06 15:18:53,336] Finished trial#65 resulted in value: 7.148371159735503. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[18500000 30900000 25900000 ... 41800000 10000000 27300000]
hello


[I 2019-08-06 15:18:59,950] Finished trial#66 resulted in value: 7.4106321322666036. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[20000000 40000000 24300000 ... 28000000 22500000 36800000]
hello


[I 2019-08-06 15:19:05,962] Finished trial#67 resulted in value: 7.295160075978903. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[35300000 36800000 26000000 ... 43000000 25300000 22800000]
hello


[I 2019-08-06 15:19:14,468] Finished trial#68 resulted in value: 7.058691670334488. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[30800000 26800000 20300000 ... 28500000 34948100  9000000]
hello


[I 2019-08-06 15:19:24,354] Finished trial#69 resulted in value: 7.920149930528275. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[26500000 20500000 21800000 ... 26500000 25500000 21800000]
hello


[I 2019-08-06 15:19:34,745] Finished trial#70 resulted in value: 6.983005498140585. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[32300000 27800000 26000000 ... 34900000 19300000 25000000]
hello


[I 2019-08-06 15:19:46,386] Finished trial#71 resulted in value: 9.217688293605008. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[31900000 35300000 24800000 ... 28800000 32000000 30868149]
hello


[I 2019-08-06 15:19:57,673] Finished trial#72 resulted in value: 6.904766872125352. Current best value is 6.794033244831953 with parameters: {'num_leaves': 32, 'learning_rate': 0.022722003044537697, 'drop_rate': 4.218008912534014e-05, 'skip_drop': 0.06205021995514399}.


(1292,)
[22000000 33400000 15800000 ... 28000000 17800000 27000000]
hello


[I 2019-08-06 15:20:09,085] Finished trial#73 resulted in value: 6.664340936383219. Current best value is 6.664340936383219 with parameters: {'num_leaves': 86, 'learning_rate': 0.013999286918386032, 'drop_rate': 4.989644495345875e-08, 'skip_drop': 0.0015792794620666545}.


(1292,)
[23800000 28000000 29300000 ... 25800000 31300000 23800000]
hello


[I 2019-08-06 15:20:23,730] Finished trial#74 resulted in value: 18.461827614235805. Current best value is 6.664340936383219 with parameters: {'num_leaves': 86, 'learning_rate': 0.013999286918386032, 'drop_rate': 4.989644495345875e-08, 'skip_drop': 0.0015792794620666545}.


(1292,)
[26800000 35900000 27800000 ... 17800000 33800000 18300000]
hello


[I 2019-08-06 15:20:34,896] Finished trial#75 resulted in value: 18.75525283913071. Current best value is 6.664340936383219 with parameters: {'num_leaves': 86, 'learning_rate': 0.013999286918386032, 'drop_rate': 4.989644495345875e-08, 'skip_drop': 0.0015792794620666545}.


(1292,)
[28800000 27500000 26900000 ... 19600000 27300000 24900000]
hello


[I 2019-08-06 15:20:47,818] Finished trial#76 resulted in value: 13.956813547644863. Current best value is 6.664340936383219 with parameters: {'num_leaves': 86, 'learning_rate': 0.013999286918386032, 'drop_rate': 4.989644495345875e-08, 'skip_drop': 0.0015792794620666545}.


(1292,)
[42980000 31200000 21700000 ... 27990000 28600000 25800000]
hello


[I 2019-08-06 15:21:00,759] Finished trial#77 resulted in value: 7.2343908746766035. Current best value is 6.664340936383219 with parameters: {'num_leaves': 86, 'learning_rate': 0.013999286918386032, 'drop_rate': 4.989644495345875e-08, 'skip_drop': 0.0015792794620666545}.


(1292,)
[18200000 45800000 24900000 ... 19500000 27192593 16500000]
hello


[I 2019-08-06 15:21:13,213] Finished trial#78 resulted in value: 7.369350585139961. Current best value is 6.664340936383219 with parameters: {'num_leaves': 86, 'learning_rate': 0.013999286918386032, 'drop_rate': 4.989644495345875e-08, 'skip_drop': 0.0015792794620666545}.


(1292,)
[28300000 28990000 21800000 ... 29000000 13800000 25800000]
hello


[I 2019-08-06 15:21:25,922] Finished trial#79 resulted in value: 6.543919431673996. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[34800000 33500000 34000000 ... 19800000 24000000 30200000]
hello


[I 2019-08-06 15:21:37,802] Finished trial#80 resulted in value: 7.549559932442188. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[43800000 19900000 18800000 ... 27800000 33800000 18900000]
hello


[I 2019-08-06 15:21:50,402] Finished trial#81 resulted in value: 8.390351152253654. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[21500000 22300000 40990000 ... 22000000 31000000 26500000]
hello


[I 2019-08-06 15:22:01,790] Finished trial#82 resulted in value: 11.161645681037353. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[21800000 28700000 57000000 ... 21380700 27500000 35000000]
hello


[I 2019-08-06 15:22:13,478] Finished trial#83 resulted in value: 12.652761694685912. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[36800000 29000000 25200000 ... 25800000 13200000 20000000]
hello


[I 2019-08-06 15:22:24,660] Finished trial#84 resulted in value: 19.748188430662175. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[ 5500000 33500000 34000000 ... 45800000 26800000 26200000]
hello


[I 2019-08-06 15:22:35,665] Finished trial#85 resulted in value: 10.086399893210654. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[31000000 24900000 24200000 ... 22800000 23900000 14700000]
hello


[I 2019-08-06 15:22:46,513] Finished trial#86 resulted in value: 7.566909599649439. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[17500000 16300000 17600000 ... 28800000 20000000 22500000]
hello


[I 2019-08-06 15:22:56,127] Finished trial#87 resulted in value: 7.298558782815739. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[32000000 28000000 28000000 ... 28300000 25256842 26300000]
hello


[I 2019-08-06 15:23:08,438] Finished trial#88 resulted in value: 6.989000538621097. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[21800000 41500000 32990000 ... 19500000 21200000 32500000]
hello


[I 2019-08-06 15:23:51,090] Finished trial#89 resulted in value: 12.224642794643614. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[23500000 33900000 31800000 ... 26800000 24000000 30500000]
hello


[I 2019-08-06 15:24:01,609] Finished trial#90 resulted in value: 16.196886127897447. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[25900000 31800000 32800000 ... 27000000 30800000 24800000]
hello


[I 2019-08-06 15:24:13,269] Finished trial#91 resulted in value: 18.866093241140142. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[36800000 33800000 32500000 ... 23000000 24990000 29900000]
hello


[I 2019-08-06 15:24:27,381] Finished trial#92 resulted in value: 64.41290704614127. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[38400000 39900000 25900000 ... 26000000 33900000 19700000]
hello


[I 2019-08-06 15:24:37,587] Finished trial#93 resulted in value: 9.732366043584218. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[29000000 35700000 43000000 ... 28500000 38000000 22800000]
hello


[I 2019-08-06 15:24:47,119] Finished trial#94 resulted in value: 6.81887350270856. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[29800000 18300000 29900000 ... 17800000 24300000 29500000]
hello


[I 2019-08-06 15:24:58,497] Finished trial#95 resulted in value: 20.388403883418242. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[24500000 24800000 23800000 ... 31000000 19800000 42800000]
hello


[I 2019-08-06 15:25:07,717] Finished trial#96 resulted in value: 7.230256472945003. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[29300000 18600000 30800000 ... 26300000 38900000 23800000]
hello


[I 2019-08-06 15:25:20,227] Finished trial#97 resulted in value: 8.194290608631878. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[42000000 45980000 25000000 ... 23300000 31000000 29500000]
hello


[I 2019-08-06 15:25:24,822] Finished trial#98 resulted in value: 7.148883521178065. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


(1292,)
[22000000 15000000 27400000 ... 27800000 10800000 38000000]
hello


[I 2019-08-06 15:25:33,642] Finished trial#99 resulted in value: 13.206510086409695. Current best value is 6.543919431673996 with parameters: {'num_leaves': 89, 'learning_rate': 0.020995848649768882, 'drop_rate': 2.0304129928302412e-07, 'skip_drop': 0.003965941780322623}.


Number of finished trials: 100
Best trial:
  Value: 6.543919431673996
  Params: 
    num_leaves: 89
    learning_rate: 0.020995848649768882
    drop_rate: 2.0304129928302412e-07
    skip_drop: 0.003965941780322623


# データ整形

In [ ]:
#必要な列だけ残す
X = train_input.drop(['id','pj_no','keiyaku_pr'],axis = 1)
X_test = test_input.drop(['id','pj_no'],axis = 1)
y = train_input[['keiyaku_pr']]

Parameter_df =pd.DataFrame()
MAPE_df = pd.DataFrame()
MAPE_train_df =pd.DataFrame()
Submit_df = test_input[['id']].copy(deep = True)
Submit_df['MAPE_sum'] = 0

#グループ分けの定義
groups = train_input['pj_no'].array


#gkf = GroupShuffleSplit(test_size =0.2,random_state=0)
kf = KFold(n_splits= 5,shuffle=True,random_state=0)

i = 0
#for train,valid  in tqdm(gkf.split(X, y,groups=groups)):
for train,valid in tqdm(kf.split(X,y)):
    X_train = X.iloc[train.tolist()]
    X_valid = X.iloc[valid.tolist()]
    y_train = y.iloc[train.tolist()]
    y_valid = y.iloc[valid.tolist()]

#     # 学習データと検証データに分割する
#     #X_train, X_valid, y_train, y_valid = train_test_split(X, y,test_size = 0.2,shuffle = True,random_state = i+10)
#     X_train, X_valid, y_train, y_valid = GroupShuffleSplit(X, y,groups=train_input['pj_no'].array,test_size = 0.2,shuffle = True,random_state = i+10)

    # 上記のパラメータでモデルを学習する

    #'''
#     model = LGBMRegressorCV(
#                             n_estimators = 100,
#                             learning_rate = 0.1,
#                             n_trials = 100,
#                             n_iter_no_change=10,
#                             random_state=0,
#                             timeout = 60)
#     #'''

#     #ハイパーパラメータチューニングしない場合はこっち
#     #model = lgb.LGBMRegressor(random_state=10)

#     #学習
#     model.fit(X_train, y_train,categorical_feature=important_categorical_columns)

    lgb_train = lgb.Dataset(X_train, y_train)
    lgb_eval = lgb.Dataset(X_valid, y_valid, reference=lgb_train)
    # LightGBM parameters
    params = {
            'task' : 'train',
            'boosting_type' : 'dart',
            'objective' : 'regression',
            'metric' : {'mape'},
            'num_leaves' :89,
            'learning_rate' : 0.020995848649768882,
            'n_estimators' : 3000,
            'feature_fraction' : 0.5,
            'bagging_fraction' : 0.8,
            'bagging_freq': 5,
            'verbose' : 0,
            'drop_rate' : 2.0304129928302412e-07,
            'skip_drop' : 0.003965941780322623
    }


    # train
    model = lgb.train(params,
                lgb_train,
                num_boost_round=4000,
                valid_sets=lgb_eval,
                early_stopping_rounds=300)

    #選ばれたハイパーパラメータの記録
    #temp_parameter_df = pd.DataFrame(model.best_params_.items()).set_index(0).T
    #Parameter_df = Parameter_df.append(temp_parameter_df )

    # 検証データを予測する
    #y_pred = model.predict(X_valid)
    y_pred = model.predict(X_valid, num_iteration=model.best_iteration)
    y_pred_train = model.predict(X_train, num_iteration=model.best_iteration)

    #検証スコア算出
    y_pred_df = pd.DataFrame(y_pred)
    y_valid = y_valid.reset_index().drop('index',axis=1)
    compared = pd.concat([y_pred_df,y_valid ],axis = 1)
    compared['APE'] = abs((compared[0]-compared['keiyaku_pr'])/compared['keiyaku_pr'])
    
    #検証スコア算出(train)
    y_pred_train_df = pd.DataFrame(y_pred_train)
    y_train = y_train.reset_index().drop('index',axis=1)
    compared_train = pd.concat([y_pred_train_df,y_train ],axis = 1)
    compared_train['APE'] = abs((compared_train[0]-compared_train['keiyaku_pr'])/compared_train['keiyaku_pr'])

    #検証スコアを記録
    temp_dict = {'MAPE':compared['APE'].mean()*100}
    temp_df = pd.DataFrame(temp_dict.items()).set_index(0).T
    MAPE_df = MAPE_df.append(temp_df)

    #検証スコアを記録
    temp_dict_train = {'MAPE':compared_train['APE'].mean()*100}
    temp_train_df = pd.DataFrame(temp_dict_train.items()).set_index(0).T
    MAPE_train_df = MAPE_train_df.append(temp_train_df)
    
    #予測を実行
    #y_test_pred = model.predict(X_test)
    y_test_pred = model.predict(X_test, num_iteration=model.best_iteration)
    y_test_pred_df = pd.DataFrame(y_test_pred)

    #提出用のデータフレーム作成
    temp_submit = pd.concat([test_input[['id']],y_test_pred_df],axis=1)
    temp_submit.rename(columns={0:'MAPE_'+str(i)},inplace = True)
    Submit_df = pd.merge(Submit_df,temp_submit,on='id')

    Submit_df['MAPE_sum'] = Submit_df['MAPE_sum'] + Submit_df['MAPE_'+str(i)]
    i = i+1
    
Submit_df['MAPE_mean'] = Submit_df['MAPE_sum']/(i)
    


0it [00:00, ?it/s]

[1]	valid_0's mape: 0.213302
[2]	valid_0's mape: 0.21028
[3]	valid_0's mape: 0.207286
[4]	valid_0's mape: 0.204356
[5]	valid_0's mape: 0.201579
[6]	valid_0's mape: 0.19862
[7]	valid_0's mape: 0.195822
[8]	valid_0's mape: 0.193263
[9]	valid_0's mape: 0.190543
[10]	valid_0's mape: 0.187869
[11]	valid_0's mape: 0.185436
[12]	valid_0's mape: 0.182867
[13]	valid_0's mape: 0.180515
[14]	valid_0's mape: 0.178127
[15]	valid_0's mape: 0.175755
[16]	valid_0's mape: 0.173496
[17]	valid_0's mape: 0.171145
[18]	valid_0's mape: 0.168969
[19]	valid_0's mape: 0.166986
[20]	valid_0's mape: 0.164876
[21]	valid_0's mape: 0.162788
[22]	valid_0's mape: 0.160836
[23]	valid_0's mape: 0.158874
[24]	valid_0's mape: 0.15704
[25]	valid_0's mape: 0.15525
[26]	valid_0's mape: 0.153445
[27]	valid_0's mape: 0.151736
[28]	valid_0's mape: 0.150045
[29]	valid_0's mape: 0.148484
[30]	valid_0's mape: 0.146867
[31]	valid_0's mape: 0.145306
[32]	valid_0's mape: 0.143731
[33]	valid_0's mape: 0.142354
[34]	valid_0's mape: 0.

[263]	valid_0's mape: 0.0766506
[264]	valid_0's mape: 0.0765875
[265]	valid_0's mape: 0.0765503
[266]	valid_0's mape: 0.0765132
[267]	valid_0's mape: 0.0765075
[268]	valid_0's mape: 0.076477
[269]	valid_0's mape: 0.0764737
[270]	valid_0's mape: 0.0764623
[271]	valid_0's mape: 0.0764231
[272]	valid_0's mape: 0.0763745
[273]	valid_0's mape: 0.0763646
[274]	valid_0's mape: 0.0763295
[275]	valid_0's mape: 0.0762976
[276]	valid_0's mape: 0.0762729
[277]	valid_0's mape: 0.07623
[278]	valid_0's mape: 0.0761857
[279]	valid_0's mape: 0.0761512
[280]	valid_0's mape: 0.0761183
[281]	valid_0's mape: 0.0760932
[282]	valid_0's mape: 0.076063
[283]	valid_0's mape: 0.0760486
[284]	valid_0's mape: 0.0760321
[285]	valid_0's mape: 0.0759992
[286]	valid_0's mape: 0.0759611
[287]	valid_0's mape: 0.0759292
[288]	valid_0's mape: 0.0759104
[289]	valid_0's mape: 0.0759006
[290]	valid_0's mape: 0.0758727
[291]	valid_0's mape: 0.0758711
[292]	valid_0's mape: 0.0758522
[293]	valid_0's mape: 0.0758074
[294]	valid_

[519]	valid_0's mape: 0.0738343
[520]	valid_0's mape: 0.0738298
[521]	valid_0's mape: 0.0738218
[522]	valid_0's mape: 0.0738068
[523]	valid_0's mape: 0.0738027
[524]	valid_0's mape: 0.0738044
[525]	valid_0's mape: 0.0737912
[526]	valid_0's mape: 0.0737821
[527]	valid_0's mape: 0.0737713
[528]	valid_0's mape: 0.0737584
[529]	valid_0's mape: 0.073754
[530]	valid_0's mape: 0.0737544
[531]	valid_0's mape: 0.0737539
[532]	valid_0's mape: 0.073749
[533]	valid_0's mape: 0.0737476
[534]	valid_0's mape: 0.0737388
[535]	valid_0's mape: 0.0737339
[536]	valid_0's mape: 0.0737448
[537]	valid_0's mape: 0.0737534
[538]	valid_0's mape: 0.0737619
[539]	valid_0's mape: 0.0737665
[540]	valid_0's mape: 0.0737587
[541]	valid_0's mape: 0.0737601
[542]	valid_0's mape: 0.0737627
[543]	valid_0's mape: 0.0737653
[544]	valid_0's mape: 0.0737676
[545]	valid_0's mape: 0.0737629
[546]	valid_0's mape: 0.0737579
[547]	valid_0's mape: 0.0737481
[548]	valid_0's mape: 0.0737508
[549]	valid_0's mape: 0.0737407
[550]	vali

[775]	valid_0's mape: 0.0735545
[776]	valid_0's mape: 0.0735538
[777]	valid_0's mape: 0.0735538
[778]	valid_0's mape: 0.0735591
[779]	valid_0's mape: 0.0735505
[780]	valid_0's mape: 0.0735411
[781]	valid_0's mape: 0.0735439
[782]	valid_0's mape: 0.0735425
[783]	valid_0's mape: 0.0735414
[784]	valid_0's mape: 0.0735506
[785]	valid_0's mape: 0.0735549
[786]	valid_0's mape: 0.0735545
[787]	valid_0's mape: 0.0735517
[788]	valid_0's mape: 0.0735552
[789]	valid_0's mape: 0.073561
[790]	valid_0's mape: 0.0735574
[791]	valid_0's mape: 0.0735625
[792]	valid_0's mape: 0.0735645
[793]	valid_0's mape: 0.0735617
[794]	valid_0's mape: 0.0735646
[795]	valid_0's mape: 0.0735651
[796]	valid_0's mape: 0.0735629
[797]	valid_0's mape: 0.0735584
[798]	valid_0's mape: 0.0735549
[799]	valid_0's mape: 0.0735516
[800]	valid_0's mape: 0.0735537
[801]	valid_0's mape: 0.0735497
[802]	valid_0's mape: 0.0735418
[803]	valid_0's mape: 0.0736107
[804]	valid_0's mape: 0.0736013
[805]	valid_0's mape: 0.0736051
[806]	val

[1031]	valid_0's mape: 0.0734994
[1032]	valid_0's mape: 0.0734931
[1033]	valid_0's mape: 0.0734893
[1034]	valid_0's mape: 0.0734873
[1035]	valid_0's mape: 0.0734926
[1036]	valid_0's mape: 0.0734878
[1037]	valid_0's mape: 0.0734942
[1038]	valid_0's mape: 0.0734927
[1039]	valid_0's mape: 0.0734976
[1040]	valid_0's mape: 0.0734922
[1041]	valid_0's mape: 0.0734903
[1042]	valid_0's mape: 0.0734916
[1043]	valid_0's mape: 0.0735
[1044]	valid_0's mape: 0.0735078
[1045]	valid_0's mape: 0.0735114
[1046]	valid_0's mape: 0.0735105
[1047]	valid_0's mape: 0.0735119
[1048]	valid_0's mape: 0.0735154
[1049]	valid_0's mape: 0.0735165
[1050]	valid_0's mape: 0.0735139
[1051]	valid_0's mape: 0.0735176
[1052]	valid_0's mape: 0.0735171
[1053]	valid_0's mape: 0.0735148
[1054]	valid_0's mape: 0.0735171
[1055]	valid_0's mape: 0.0735155
[1056]	valid_0's mape: 0.073512
[1057]	valid_0's mape: 0.0735191
[1058]	valid_0's mape: 0.0735148
[1059]	valid_0's mape: 0.0735197
[1060]	valid_0's mape: 0.073519
[1061]	valid_0'

[1280]	valid_0's mape: 0.0736799
[1281]	valid_0's mape: 0.0736819
[1282]	valid_0's mape: 0.0736804
[1283]	valid_0's mape: 0.0736808
[1284]	valid_0's mape: 0.0736857
[1285]	valid_0's mape: 0.0736879
[1286]	valid_0's mape: 0.0736864
[1287]	valid_0's mape: 0.0736826
[1288]	valid_0's mape: 0.0736834
[1289]	valid_0's mape: 0.0736828
[1290]	valid_0's mape: 0.0736858
[1291]	valid_0's mape: 0.0736845
[1292]	valid_0's mape: 0.0736846
[1293]	valid_0's mape: 0.0736837
[1294]	valid_0's mape: 0.073675
[1295]	valid_0's mape: 0.073672
[1296]	valid_0's mape: 0.0736754
[1297]	valid_0's mape: 0.0736787
[1298]	valid_0's mape: 0.0736789
[1299]	valid_0's mape: 0.0736781
[1300]	valid_0's mape: 0.0736807
[1301]	valid_0's mape: 0.0736795
[1302]	valid_0's mape: 0.0736773
[1303]	valid_0's mape: 0.0736767
[1304]	valid_0's mape: 0.0736792
[1305]	valid_0's mape: 0.0736827
[1306]	valid_0's mape: 0.0736798
[1307]	valid_0's mape: 0.0736761
[1308]	valid_0's mape: 0.0736731
[1309]	valid_0's mape: 0.0736717
[1310]	valid

[1528]	valid_0's mape: 0.0738475
[1529]	valid_0's mape: 0.0738432
[1530]	valid_0's mape: 0.0738493
[1531]	valid_0's mape: 0.0738479
[1532]	valid_0's mape: 0.0738458
[1533]	valid_0's mape: 0.0738442
[1534]	valid_0's mape: 0.0738433
[1535]	valid_0's mape: 0.0738447
[1536]	valid_0's mape: 0.0738402
[1537]	valid_0's mape: 0.0738354
[1538]	valid_0's mape: 0.0738378
[1539]	valid_0's mape: 0.0738407
[1540]	valid_0's mape: 0.0738419
[1541]	valid_0's mape: 0.0738387
[1542]	valid_0's mape: 0.0738391
[1543]	valid_0's mape: 0.0738387
[1544]	valid_0's mape: 0.0738422
[1545]	valid_0's mape: 0.0738373
[1546]	valid_0's mape: 0.0738328
[1547]	valid_0's mape: 0.0738355
[1548]	valid_0's mape: 0.0738367
[1549]	valid_0's mape: 0.0738364
[1550]	valid_0's mape: 0.0738368
[1551]	valid_0's mape: 0.0738392
[1552]	valid_0's mape: 0.073839
[1553]	valid_0's mape: 0.0738377
[1554]	valid_0's mape: 0.0738367
[1555]	valid_0's mape: 0.0738329
[1556]	valid_0's mape: 0.073835
[1557]	valid_0's mape: 0.0738354
[1558]	valid

[1777]	valid_0's mape: 0.0740113
[1778]	valid_0's mape: 0.0740104
[1779]	valid_0's mape: 0.0740094
[1780]	valid_0's mape: 0.0740127
[1781]	valid_0's mape: 0.0740141
[1782]	valid_0's mape: 0.0740137
[1783]	valid_0's mape: 0.0740124
[1784]	valid_0's mape: 0.074016
[1785]	valid_0's mape: 0.0740114
[1786]	valid_0's mape: 0.074013
[1787]	valid_0's mape: 0.0740113
[1788]	valid_0's mape: 0.074013
[1789]	valid_0's mape: 0.0740134
[1790]	valid_0's mape: 0.0740114
[1791]	valid_0's mape: 0.074011
[1792]	valid_0's mape: 0.0740135
[1793]	valid_0's mape: 0.0740143
[1794]	valid_0's mape: 0.0740136
[1795]	valid_0's mape: 0.0740133
[1796]	valid_0's mape: 0.0740125
[1797]	valid_0's mape: 0.0740151
[1798]	valid_0's mape: 0.0740207
[1799]	valid_0's mape: 0.0740207
[1800]	valid_0's mape: 0.0740207
[1801]	valid_0's mape: 0.0740178
[1802]	valid_0's mape: 0.0740141
[1803]	valid_0's mape: 0.0740126
[1804]	valid_0's mape: 0.0740129
[1805]	valid_0's mape: 0.0740139
[1806]	valid_0's mape: 0.074013
[1807]	valid_0'

[2026]	valid_0's mape: 0.0741275
[2027]	valid_0's mape: 0.0741249
[2028]	valid_0's mape: 0.0741251
[2029]	valid_0's mape: 0.0741233
[2030]	valid_0's mape: 0.0741187
[2031]	valid_0's mape: 0.0741198
[2032]	valid_0's mape: 0.0741205
[2033]	valid_0's mape: 0.0741193
[2034]	valid_0's mape: 0.0741156
[2035]	valid_0's mape: 0.0741127
[2036]	valid_0's mape: 0.0741153
[2037]	valid_0's mape: 0.0741152
[2038]	valid_0's mape: 0.0741153
[2039]	valid_0's mape: 0.0741145
[2040]	valid_0's mape: 0.0741152
[2041]	valid_0's mape: 0.0741171
[2042]	valid_0's mape: 0.0741172
[2043]	valid_0's mape: 0.0741161
[2044]	valid_0's mape: 0.0741177
[2045]	valid_0's mape: 0.0741195
[2046]	valid_0's mape: 0.0741161
[2047]	valid_0's mape: 0.0741167
[2048]	valid_0's mape: 0.0741203
[2049]	valid_0's mape: 0.0741144
[2050]	valid_0's mape: 0.0741129
[2051]	valid_0's mape: 0.0741134
[2052]	valid_0's mape: 0.0741128
[2053]	valid_0's mape: 0.0741147
[2054]	valid_0's mape: 0.0741121
[2055]	valid_0's mape: 0.0741098
[2056]	val

[2275]	valid_0's mape: 0.0740926
[2276]	valid_0's mape: 0.0740904
[2277]	valid_0's mape: 0.0740905
[2278]	valid_0's mape: 0.0740906
[2279]	valid_0's mape: 0.0740901
[2280]	valid_0's mape: 0.0740898
[2281]	valid_0's mape: 0.0740919
[2282]	valid_0's mape: 0.0740925
[2283]	valid_0's mape: 0.0740912
[2284]	valid_0's mape: 0.0740929
[2285]	valid_0's mape: 0.0740932
[2286]	valid_0's mape: 0.0740956
[2287]	valid_0's mape: 0.0740986
[2288]	valid_0's mape: 0.0740996
[2289]	valid_0's mape: 0.074102
[2290]	valid_0's mape: 0.0741051
[2291]	valid_0's mape: 0.0741088
[2292]	valid_0's mape: 0.0741131
[2293]	valid_0's mape: 0.0741134
[2294]	valid_0's mape: 0.074112
[2295]	valid_0's mape: 0.0741138
[2296]	valid_0's mape: 0.0741129
[2297]	valid_0's mape: 0.0741132
[2298]	valid_0's mape: 0.0741133
[2299]	valid_0's mape: 0.074109
[2300]	valid_0's mape: 0.0741106
[2301]	valid_0's mape: 0.0741117
[2302]	valid_0's mape: 0.0741068
[2303]	valid_0's mape: 0.0740993
[2304]	valid_0's mape: 0.0740981
[2305]	valid_

[2524]	valid_0's mape: 0.0742422
[2525]	valid_0's mape: 0.0742446
[2526]	valid_0's mape: 0.0742453
[2527]	valid_0's mape: 0.0742449
[2528]	valid_0's mape: 0.0742452
[2529]	valid_0's mape: 0.0742461
[2530]	valid_0's mape: 0.0742472
[2531]	valid_0's mape: 0.0742483
[2532]	valid_0's mape: 0.074253
[2533]	valid_0's mape: 0.0742533
[2534]	valid_0's mape: 0.0742547
[2535]	valid_0's mape: 0.0742564
[2536]	valid_0's mape: 0.0742591
[2537]	valid_0's mape: 0.0742586
[2538]	valid_0's mape: 0.0742593
[2539]	valid_0's mape: 0.0742597
[2540]	valid_0's mape: 0.0742613
[2541]	valid_0's mape: 0.0742611
[2542]	valid_0's mape: 0.0742622
[2543]	valid_0's mape: 0.0742647
[2544]	valid_0's mape: 0.074266
[2545]	valid_0's mape: 0.0742677
[2546]	valid_0's mape: 0.0742671
[2547]	valid_0's mape: 0.0742677
[2548]	valid_0's mape: 0.0742668
[2549]	valid_0's mape: 0.0742641
[2550]	valid_0's mape: 0.0742644
[2551]	valid_0's mape: 0.0742652
[2552]	valid_0's mape: 0.074266
[2553]	valid_0's mape: 0.0742681
[2554]	valid_

[2773]	valid_0's mape: 0.0743055
[2774]	valid_0's mape: 0.0743054
[2775]	valid_0's mape: 0.0743051
[2776]	valid_0's mape: 0.0743082
[2777]	valid_0's mape: 0.074305
[2778]	valid_0's mape: 0.0743054
[2779]	valid_0's mape: 0.0743025
[2780]	valid_0's mape: 0.0743024
[2781]	valid_0's mape: 0.0743058
[2782]	valid_0's mape: 0.0743067
[2783]	valid_0's mape: 0.0743058
[2784]	valid_0's mape: 0.0743031
[2785]	valid_0's mape: 0.0743039
[2786]	valid_0's mape: 0.0743044
[2787]	valid_0's mape: 0.074306
[2788]	valid_0's mape: 0.0743069
[2789]	valid_0's mape: 0.0743083
[2790]	valid_0's mape: 0.0743115
[2791]	valid_0's mape: 0.0743144
[2792]	valid_0's mape: 0.0743134
[2793]	valid_0's mape: 0.0743118
[2794]	valid_0's mape: 0.0743115
[2795]	valid_0's mape: 0.0743118
[2796]	valid_0's mape: 0.0743143
[2797]	valid_0's mape: 0.074314
[2798]	valid_0's mape: 0.0743175
[2799]	valid_0's mape: 0.07432
[2800]	valid_0's mape: 0.0743199
[2801]	valid_0's mape: 0.0743215
[2802]	valid_0's mape: 0.0743223
[2803]	valid_0'


1it [01:49, 109.74s/it]

[1]	valid_0's mape: 0.193567
[2]	valid_0's mape: 0.1909
[3]	valid_0's mape: 0.188325
[4]	valid_0's mape: 0.185849
[5]	valid_0's mape: 0.183246
[6]	valid_0's mape: 0.180724
[7]	valid_0's mape: 0.178346
[8]	valid_0's mape: 0.175946
[9]	valid_0's mape: 0.173531
[10]	valid_0's mape: 0.171318
[11]	valid_0's mape: 0.169048
[12]	valid_0's mape: 0.166808
[13]	valid_0's mape: 0.164684
[14]	valid_0's mape: 0.162588
[15]	valid_0's mape: 0.160567
[16]	valid_0's mape: 0.158624
[17]	valid_0's mape: 0.156631
[18]	valid_0's mape: 0.154708
[19]	valid_0's mape: 0.152913
[20]	valid_0's mape: 0.151035
[21]	valid_0's mape: 0.149267
[22]	valid_0's mape: 0.147542
[23]	valid_0's mape: 0.145859
[24]	valid_0's mape: 0.1441
[25]	valid_0's mape: 0.142474
[26]	valid_0's mape: 0.140947
[27]	valid_0's mape: 0.139433
[28]	valid_0's mape: 0.137864
[29]	valid_0's mape: 0.136325
[30]	valid_0's mape: 0.134853
[31]	valid_0's mape: 0.133478
[32]	valid_0's mape: 0.13217
[33]	valid_0's mape: 0.130891
[34]	valid_0's mape: 0.1

[263]	valid_0's mape: 0.0734935
[264]	valid_0's mape: 0.0734779
[265]	valid_0's mape: 0.0734381
[266]	valid_0's mape: 0.0734093
[267]	valid_0's mape: 0.0733823
[268]	valid_0's mape: 0.0733479
[269]	valid_0's mape: 0.073318
[270]	valid_0's mape: 0.073286
[271]	valid_0's mape: 0.0732677
[272]	valid_0's mape: 0.0732577
[273]	valid_0's mape: 0.0732366
[274]	valid_0's mape: 0.0731866
[275]	valid_0's mape: 0.0731745
[276]	valid_0's mape: 0.0731519
[277]	valid_0's mape: 0.0731201
[278]	valid_0's mape: 0.0731025
[279]	valid_0's mape: 0.0730884
[280]	valid_0's mape: 0.0730635
[281]	valid_0's mape: 0.0730309
[282]	valid_0's mape: 0.0730155
[283]	valid_0's mape: 0.0729713
[284]	valid_0's mape: 0.0729357
[285]	valid_0's mape: 0.0729229
[286]	valid_0's mape: 0.0728895
[287]	valid_0's mape: 0.0728775
[288]	valid_0's mape: 0.0728585
[289]	valid_0's mape: 0.0728414
[290]	valid_0's mape: 0.0728381
[291]	valid_0's mape: 0.0728098
[292]	valid_0's mape: 0.0727709
[293]	valid_0's mape: 0.0727414
[294]	vali

[520]	valid_0's mape: 0.0704462
[521]	valid_0's mape: 0.0704447
[522]	valid_0's mape: 0.0704447
[523]	valid_0's mape: 0.0704442
[524]	valid_0's mape: 0.0704441
[525]	valid_0's mape: 0.070436
[526]	valid_0's mape: 0.0704251
[527]	valid_0's mape: 0.0704222
[528]	valid_0's mape: 0.0704114
[529]	valid_0's mape: 0.0703976
[530]	valid_0's mape: 0.0703926
[531]	valid_0's mape: 0.0703883
[532]	valid_0's mape: 0.0703886
[533]	valid_0's mape: 0.0703951
[534]	valid_0's mape: 0.0703958
[535]	valid_0's mape: 0.0703899
[536]	valid_0's mape: 0.0703794
[537]	valid_0's mape: 0.0703814
[538]	valid_0's mape: 0.070382
[539]	valid_0's mape: 0.0703873
[540]	valid_0's mape: 0.0703806
[541]	valid_0's mape: 0.0703805
[542]	valid_0's mape: 0.0703764
[543]	valid_0's mape: 0.0703745
[544]	valid_0's mape: 0.070377
[545]	valid_0's mape: 0.0703647
[546]	valid_0's mape: 0.0703655
[547]	valid_0's mape: 0.0703739
[548]	valid_0's mape: 0.0703683
[549]	valid_0's mape: 0.0703637
[550]	valid_0's mape: 0.0703687
[551]	valid

[776]	valid_0's mape: 0.0701138
[777]	valid_0's mape: 0.0701167
[778]	valid_0's mape: 0.0701156
[779]	valid_0's mape: 0.0701207
[780]	valid_0's mape: 0.0701239
[781]	valid_0's mape: 0.0701244
[782]	valid_0's mape: 0.0701193
[783]	valid_0's mape: 0.0701245
[784]	valid_0's mape: 0.0701279
[785]	valid_0's mape: 0.0701276
[786]	valid_0's mape: 0.0701208
[787]	valid_0's mape: 0.0701149
[788]	valid_0's mape: 0.0701057
[789]	valid_0's mape: 0.0701189
[790]	valid_0's mape: 0.0701162
[791]	valid_0's mape: 0.0701138
[792]	valid_0's mape: 0.0701135
[793]	valid_0's mape: 0.0701103
[794]	valid_0's mape: 0.0701143
[795]	valid_0's mape: 0.070115
[796]	valid_0's mape: 0.0701194
[797]	valid_0's mape: 0.0701054
[798]	valid_0's mape: 0.0700961
[799]	valid_0's mape: 0.0700973
[800]	valid_0's mape: 0.0701019
[801]	valid_0's mape: 0.0700942
[802]	valid_0's mape: 0.0700814
[803]	valid_0's mape: 0.0701483
[804]	valid_0's mape: 0.0701434
[805]	valid_0's mape: 0.0701348
[806]	valid_0's mape: 0.0701437
[807]	val

[1031]	valid_0's mape: 0.0700607
[1032]	valid_0's mape: 0.0700636
[1033]	valid_0's mape: 0.0700641
[1034]	valid_0's mape: 0.0700581
[1035]	valid_0's mape: 0.0700562
[1036]	valid_0's mape: 0.070057
[1037]	valid_0's mape: 0.0700558
[1038]	valid_0's mape: 0.0700583
[1039]	valid_0's mape: 0.0700609
[1040]	valid_0's mape: 0.0700636
[1041]	valid_0's mape: 0.0700579
[1042]	valid_0's mape: 0.0700586
[1043]	valid_0's mape: 0.0700605
[1044]	valid_0's mape: 0.0700629
[1045]	valid_0's mape: 0.070063
[1046]	valid_0's mape: 0.0700601
[1047]	valid_0's mape: 0.0700622
[1048]	valid_0's mape: 0.0700604
[1049]	valid_0's mape: 0.0700619
[1050]	valid_0's mape: 0.0700606
[1051]	valid_0's mape: 0.0700589
[1052]	valid_0's mape: 0.070058
[1053]	valid_0's mape: 0.0700615
[1054]	valid_0's mape: 0.0700618
[1055]	valid_0's mape: 0.0700642
[1056]	valid_0's mape: 0.0700636
[1057]	valid_0's mape: 0.0700615
[1058]	valid_0's mape: 0.0700595
[1059]	valid_0's mape: 0.0700589
[1060]	valid_0's mape: 0.0700541
[1061]	valid_

[1280]	valid_0's mape: 0.0703272
[1281]	valid_0's mape: 0.0703266
[1282]	valid_0's mape: 0.0703255
[1283]	valid_0's mape: 0.0703288
[1284]	valid_0's mape: 0.0703244
[1285]	valid_0's mape: 0.0703228
[1286]	valid_0's mape: 0.0703265
[1287]	valid_0's mape: 0.0703224
[1288]	valid_0's mape: 0.0703213
[1289]	valid_0's mape: 0.0703206
[1290]	valid_0's mape: 0.0703206
[1291]	valid_0's mape: 0.0703221
[1292]	valid_0's mape: 0.0703255
[1293]	valid_0's mape: 0.0703312
[1294]	valid_0's mape: 0.0703342
[1295]	valid_0's mape: 0.0703319
[1296]	valid_0's mape: 0.0703318
[1297]	valid_0's mape: 0.0703327
[1298]	valid_0's mape: 0.0703326
[1299]	valid_0's mape: 0.0703361
[1300]	valid_0's mape: 0.0703367
[1301]	valid_0's mape: 0.0703407
[1302]	valid_0's mape: 0.0703366
[1303]	valid_0's mape: 0.0703364
[1304]	valid_0's mape: 0.0703336
[1305]	valid_0's mape: 0.0703313
[1306]	valid_0's mape: 0.0703342
[1307]	valid_0's mape: 0.0703323
[1308]	valid_0's mape: 0.0703306
[1309]	valid_0's mape: 0.0703267
[1310]	val

[1528]	valid_0's mape: 0.070539
[1529]	valid_0's mape: 0.0705422
[1530]	valid_0's mape: 0.0705435
[1531]	valid_0's mape: 0.0705492
[1532]	valid_0's mape: 0.0705489
[1533]	valid_0's mape: 0.0705522
[1534]	valid_0's mape: 0.0705546
[1535]	valid_0's mape: 0.0705601
[1536]	valid_0's mape: 0.0705637
[1537]	valid_0's mape: 0.0705647
[1538]	valid_0's mape: 0.0705629
[1539]	valid_0's mape: 0.0705654
[1540]	valid_0's mape: 0.0705662
[1541]	valid_0's mape: 0.0705658
[1542]	valid_0's mape: 0.0705639
[1543]	valid_0's mape: 0.070564
[1544]	valid_0's mape: 0.070564
[1545]	valid_0's mape: 0.0705669
[1546]	valid_0's mape: 0.0705645
[1547]	valid_0's mape: 0.0705639
[1548]	valid_0's mape: 0.0705632
[1549]	valid_0's mape: 0.070563
[1550]	valid_0's mape: 0.070565
[1551]	valid_0's mape: 0.0705641
[1552]	valid_0's mape: 0.0705606
[1553]	valid_0's mape: 0.0705633
[1554]	valid_0's mape: 0.0705566
[1555]	valid_0's mape: 0.0705549
[1556]	valid_0's mape: 0.0705548
[1557]	valid_0's mape: 0.0705567
[1558]	valid_0'

[1777]	valid_0's mape: 0.0707344
[1778]	valid_0's mape: 0.0707361
[1779]	valid_0's mape: 0.0707347
[1780]	valid_0's mape: 0.0707375
[1781]	valid_0's mape: 0.0707346
[1782]	valid_0's mape: 0.070734
[1783]	valid_0's mape: 0.0707345
[1784]	valid_0's mape: 0.070732
[1785]	valid_0's mape: 0.0707335
[1786]	valid_0's mape: 0.0707349
[1787]	valid_0's mape: 0.0707342
[1788]	valid_0's mape: 0.0707347
[1789]	valid_0's mape: 0.0707361
[1790]	valid_0's mape: 0.0707381
[1791]	valid_0's mape: 0.0707396
[1792]	valid_0's mape: 0.0707421
[1793]	valid_0's mape: 0.070745
[1794]	valid_0's mape: 0.0707492
[1795]	valid_0's mape: 0.0707497
[1796]	valid_0's mape: 0.0707494
[1797]	valid_0's mape: 0.070752
[1798]	valid_0's mape: 0.0707469
[1799]	valid_0's mape: 0.0707513
[1800]	valid_0's mape: 0.070751
[1801]	valid_0's mape: 0.0707507
[1802]	valid_0's mape: 0.0707548
[1803]	valid_0's mape: 0.070758
[1804]	valid_0's mape: 0.0707589
[1805]	valid_0's mape: 0.0707597
[1806]	valid_0's mape: 0.0707622
[1807]	valid_0's

[2026]	valid_0's mape: 0.0709043
[2027]	valid_0's mape: 0.0709036
[2028]	valid_0's mape: 0.0709014
[2029]	valid_0's mape: 0.0709021
[2030]	valid_0's mape: 0.0709007
[2031]	valid_0's mape: 0.0708987
[2032]	valid_0's mape: 0.0708993
[2033]	valid_0's mape: 0.070899
[2034]	valid_0's mape: 0.0709005
[2035]	valid_0's mape: 0.0708997
[2036]	valid_0's mape: 0.0708978
[2037]	valid_0's mape: 0.0708956
[2038]	valid_0's mape: 0.0708949
[2039]	valid_0's mape: 0.070891
[2040]	valid_0's mape: 0.0708911
[2041]	valid_0's mape: 0.0708925
[2042]	valid_0's mape: 0.0708962
[2043]	valid_0's mape: 0.0708962
[2044]	valid_0's mape: 0.0708963
[2045]	valid_0's mape: 0.0708965
[2046]	valid_0's mape: 0.0709002
[2047]	valid_0's mape: 0.0709011
[2048]	valid_0's mape: 0.0709035
[2049]	valid_0's mape: 0.0709044
[2050]	valid_0's mape: 0.0709032
[2051]	valid_0's mape: 0.0709048
[2052]	valid_0's mape: 0.0709087
[2053]	valid_0's mape: 0.070913
[2054]	valid_0's mape: 0.0709139
[2055]	valid_0's mape: 0.0709166
[2056]	valid_

[2275]	valid_0's mape: 0.0709345
[2276]	valid_0's mape: 0.0709353
[2277]	valid_0's mape: 0.0709404
[2278]	valid_0's mape: 0.07094
[2279]	valid_0's mape: 0.0709415
[2280]	valid_0's mape: 0.0709409
[2281]	valid_0's mape: 0.070943
[2282]	valid_0's mape: 0.0709433
[2283]	valid_0's mape: 0.0709443
[2284]	valid_0's mape: 0.070943
[2285]	valid_0's mape: 0.0709463
[2286]	valid_0's mape: 0.0709491
[2287]	valid_0's mape: 0.070952
[2288]	valid_0's mape: 0.0709557
[2289]	valid_0's mape: 0.0709571
[2290]	valid_0's mape: 0.0709568
[2291]	valid_0's mape: 0.0709544
[2292]	valid_0's mape: 0.0709553
[2293]	valid_0's mape: 0.0709559
[2294]	valid_0's mape: 0.0709574
[2295]	valid_0's mape: 0.0709565
[2296]	valid_0's mape: 0.0709554
[2297]	valid_0's mape: 0.0709566
[2298]	valid_0's mape: 0.0709575
[2299]	valid_0's mape: 0.0709563
[2300]	valid_0's mape: 0.0709597
[2301]	valid_0's mape: 0.07096
[2302]	valid_0's mape: 0.0709589
[2303]	valid_0's mape: 0.0709549
[2304]	valid_0's mape: 0.0709572
[2305]	valid_0's 

[2524]	valid_0's mape: 0.0709949
[2525]	valid_0's mape: 0.0709952
[2526]	valid_0's mape: 0.0709955
[2527]	valid_0's mape: 0.0709971
[2528]	valid_0's mape: 0.0709992
[2529]	valid_0's mape: 0.0710005
[2530]	valid_0's mape: 0.0710022
[2531]	valid_0's mape: 0.0710023
[2532]	valid_0's mape: 0.0710013
[2533]	valid_0's mape: 0.0709997
[2534]	valid_0's mape: 0.0709997
[2535]	valid_0's mape: 0.0709998
[2536]	valid_0's mape: 0.0710002
[2537]	valid_0's mape: 0.0710007
[2538]	valid_0's mape: 0.0709999
[2539]	valid_0's mape: 0.0710002
[2540]	valid_0's mape: 0.0710018
[2541]	valid_0's mape: 0.0710033
[2542]	valid_0's mape: 0.0710073
[2543]	valid_0's mape: 0.0710097
[2544]	valid_0's mape: 0.0710072
[2545]	valid_0's mape: 0.0710075
[2546]	valid_0's mape: 0.0710069
[2547]	valid_0's mape: 0.0710064
[2548]	valid_0's mape: 0.0710052
[2549]	valid_0's mape: 0.0710066
[2550]	valid_0's mape: 0.0710075
[2551]	valid_0's mape: 0.0710055
[2552]	valid_0's mape: 0.0710015
[2553]	valid_0's mape: 0.0710003
[2554]	val

[2772]	valid_0's mape: 0.0711062
[2773]	valid_0's mape: 0.0711055
[2774]	valid_0's mape: 0.071108
[2775]	valid_0's mape: 0.0711097
[2776]	valid_0's mape: 0.0711098
[2777]	valid_0's mape: 0.0711102
[2778]	valid_0's mape: 0.07111
[2779]	valid_0's mape: 0.071106
[2780]	valid_0's mape: 0.0711087
[2781]	valid_0's mape: 0.07111
[2782]	valid_0's mape: 0.0711094
[2783]	valid_0's mape: 0.0711096
[2784]	valid_0's mape: 0.0711076
[2785]	valid_0's mape: 0.0711067
[2786]	valid_0's mape: 0.0711054
[2787]	valid_0's mape: 0.0711055
[2788]	valid_0's mape: 0.0711063
[2789]	valid_0's mape: 0.0711049
[2790]	valid_0's mape: 0.0711031
[2791]	valid_0's mape: 0.0711046
[2792]	valid_0's mape: 0.0711062
[2793]	valid_0's mape: 0.0711057
[2794]	valid_0's mape: 0.0711096
[2795]	valid_0's mape: 0.0711089
[2796]	valid_0's mape: 0.0711086
[2797]	valid_0's mape: 0.0711091
[2798]	valid_0's mape: 0.0711101
[2799]	valid_0's mape: 0.0711129
[2800]	valid_0's mape: 0.0711119
[2801]	valid_0's mape: 0.0711134
[2802]	valid_0's


2it [04:07, 118.15s/it]

[1]	valid_0's mape: 0.200243
[2]	valid_0's mape: 0.197488
[3]	valid_0's mape: 0.194723
[4]	valid_0's mape: 0.191968
[5]	valid_0's mape: 0.189156
[6]	valid_0's mape: 0.186638
[7]	valid_0's mape: 0.184101
[8]	valid_0's mape: 0.18166
[9]	valid_0's mape: 0.179186
[10]	valid_0's mape: 0.176752
[11]	valid_0's mape: 0.17439
[12]	valid_0's mape: 0.172196
[13]	valid_0's mape: 0.169869
[14]	valid_0's mape: 0.167667
[15]	valid_0's mape: 0.165508
[16]	valid_0's mape: 0.163496
[17]	valid_0's mape: 0.161431
[18]	valid_0's mape: 0.159622
[19]	valid_0's mape: 0.157641
[20]	valid_0's mape: 0.15567
[21]	valid_0's mape: 0.153824
[22]	valid_0's mape: 0.151998
[23]	valid_0's mape: 0.150158
[24]	valid_0's mape: 0.148492
[25]	valid_0's mape: 0.146698
[26]	valid_0's mape: 0.14497
[27]	valid_0's mape: 0.143416
[28]	valid_0's mape: 0.14181
[29]	valid_0's mape: 0.140272
[30]	valid_0's mape: 0.138797
[31]	valid_0's mape: 0.137288
[32]	valid_0's mape: 0.135861
[33]	valid_0's mape: 0.134484
[34]	valid_0's mape: 0.1

[263]	valid_0's mape: 0.0715215
[264]	valid_0's mape: 0.0714958
[265]	valid_0's mape: 0.0714642
[266]	valid_0's mape: 0.0714465
[267]	valid_0's mape: 0.0714147
[268]	valid_0's mape: 0.0714041
[269]	valid_0's mape: 0.0713853
[270]	valid_0's mape: 0.0713477
[271]	valid_0's mape: 0.0713384
[272]	valid_0's mape: 0.0713204
[273]	valid_0's mape: 0.0713056
[274]	valid_0's mape: 0.0712662
[275]	valid_0's mape: 0.0712323
[276]	valid_0's mape: 0.0712008
[277]	valid_0's mape: 0.0711815
[278]	valid_0's mape: 0.0711455
[279]	valid_0's mape: 0.0711076
[280]	valid_0's mape: 0.0710845
[281]	valid_0's mape: 0.071056
[282]	valid_0's mape: 0.0710337
[283]	valid_0's mape: 0.07101
[284]	valid_0's mape: 0.0710004
[285]	valid_0's mape: 0.0709846
[286]	valid_0's mape: 0.0709659
[287]	valid_0's mape: 0.0709609
[288]	valid_0's mape: 0.0709286
[289]	valid_0's mape: 0.0708921
[290]	valid_0's mape: 0.0708809
[291]	valid_0's mape: 0.0708528
[292]	valid_0's mape: 0.0708517
[293]	valid_0's mape: 0.0708592
[294]	valid

[519]	valid_0's mape: 0.0685838
[520]	valid_0's mape: 0.068583
[521]	valid_0's mape: 0.0685853
[522]	valid_0's mape: 0.0685894
[523]	valid_0's mape: 0.068597
[524]	valid_0's mape: 0.0685863
[525]	valid_0's mape: 0.0685859
[526]	valid_0's mape: 0.0685951
[527]	valid_0's mape: 0.0685966
[528]	valid_0's mape: 0.0685945
[529]	valid_0's mape: 0.0685825
[530]	valid_0's mape: 0.0685862
[531]	valid_0's mape: 0.0685691
[532]	valid_0's mape: 0.0685608
[533]	valid_0's mape: 0.0685586
[534]	valid_0's mape: 0.0685536
[535]	valid_0's mape: 0.068553
[536]	valid_0's mape: 0.0685481
[537]	valid_0's mape: 0.0685361
[538]	valid_0's mape: 0.0685249
[539]	valid_0's mape: 0.0685104
[540]	valid_0's mape: 0.0684976
[541]	valid_0's mape: 0.0684975
[542]	valid_0's mape: 0.0684893
[543]	valid_0's mape: 0.0684777
[544]	valid_0's mape: 0.0684617
[545]	valid_0's mape: 0.0684546
[546]	valid_0's mape: 0.0684532
[547]	valid_0's mape: 0.0684387
[548]	valid_0's mape: 0.0684365
[549]	valid_0's mape: 0.0684437
[550]	valid

[776]	valid_0's mape: 0.0679829
[777]	valid_0's mape: 0.0679732
[778]	valid_0's mape: 0.0679724
[779]	valid_0's mape: 0.067967
[780]	valid_0's mape: 0.0679585
[781]	valid_0's mape: 0.0679527
[782]	valid_0's mape: 0.0679446
[783]	valid_0's mape: 0.0679464
[784]	valid_0's mape: 0.0679477
[785]	valid_0's mape: 0.0679454
[786]	valid_0's mape: 0.067943
[787]	valid_0's mape: 0.0679432
[788]	valid_0's mape: 0.0679363
[789]	valid_0's mape: 0.0679594
[790]	valid_0's mape: 0.0679508
[791]	valid_0's mape: 0.0679495
[792]	valid_0's mape: 0.0679524
[793]	valid_0's mape: 0.0679414
[794]	valid_0's mape: 0.0679358
[795]	valid_0's mape: 0.0679358
[796]	valid_0's mape: 0.0679389
[797]	valid_0's mape: 0.0679389
[798]	valid_0's mape: 0.067937
[799]	valid_0's mape: 0.0679387
[800]	valid_0's mape: 0.0679355
[801]	valid_0's mape: 0.0679382
[802]	valid_0's mape: 0.0679384
[803]	valid_0's mape: 0.0679565
[804]	valid_0's mape: 0.0679529
[805]	valid_0's mape: 0.0679529
[806]	valid_0's mape: 0.0679512
[807]	valid

[1031]	valid_0's mape: 0.0679147
[1032]	valid_0's mape: 0.0679111
[1033]	valid_0's mape: 0.0679119
[1034]	valid_0's mape: 0.0679163
[1035]	valid_0's mape: 0.0679129
[1036]	valid_0's mape: 0.0679113
[1037]	valid_0's mape: 0.0679104
[1038]	valid_0's mape: 0.0679088
[1039]	valid_0's mape: 0.0679069
[1040]	valid_0's mape: 0.0679112
[1041]	valid_0's mape: 0.0679099
[1042]	valid_0's mape: 0.0679107
[1043]	valid_0's mape: 0.0679165
[1044]	valid_0's mape: 0.067916
[1045]	valid_0's mape: 0.0679209
[1046]	valid_0's mape: 0.067921
[1047]	valid_0's mape: 0.0679153
[1048]	valid_0's mape: 0.067916
[1049]	valid_0's mape: 0.067917
[1050]	valid_0's mape: 0.0679117
[1051]	valid_0's mape: 0.0679162
[1052]	valid_0's mape: 0.0679118
[1053]	valid_0's mape: 0.0679104
[1054]	valid_0's mape: 0.06792
[1055]	valid_0's mape: 0.067925
[1056]	valid_0's mape: 0.0679216
[1057]	valid_0's mape: 0.0679229
[1058]	valid_0's mape: 0.067918
[1059]	valid_0's mape: 0.0679135
[1060]	valid_0's mape: 0.0679095
[1061]	valid_0's m

[1280]	valid_0's mape: 0.0680976
[1281]	valid_0's mape: 0.0680935
[1282]	valid_0's mape: 0.0680902
[1283]	valid_0's mape: 0.0680919
[1284]	valid_0's mape: 0.0680903
[1285]	valid_0's mape: 0.0680905
[1286]	valid_0's mape: 0.0680893
[1287]	valid_0's mape: 0.0680841
[1288]	valid_0's mape: 0.0680873
[1289]	valid_0's mape: 0.0680892
[1290]	valid_0's mape: 0.0680904
[1291]	valid_0's mape: 0.0680885
[1292]	valid_0's mape: 0.0680845
[1293]	valid_0's mape: 0.0680882
[1294]	valid_0's mape: 0.0680868
[1295]	valid_0's mape: 0.0680883
[1296]	valid_0's mape: 0.0680907
[1297]	valid_0's mape: 0.0680911
[1298]	valid_0's mape: 0.0680896
[1299]	valid_0's mape: 0.0680955
[1300]	valid_0's mape: 0.0680976
[1301]	valid_0's mape: 0.0680986
[1302]	valid_0's mape: 0.0681024
[1303]	valid_0's mape: 0.0681027
[1304]	valid_0's mape: 0.0681016
[1305]	valid_0's mape: 0.0680981
[1306]	valid_0's mape: 0.0680994
[1307]	valid_0's mape: 0.0680985
[1308]	valid_0's mape: 0.068099
[1309]	valid_0's mape: 0.0681051
[1310]	vali

In [52]:
#ハイパーパラメータ確認
Parameter_df

Empty DataFrame
Columns: []
Index: []

In [53]:
#各回でのMAPE検証値
MAPE_df

0      MAPE
1  7.191017
1  6.723687
1  6.622930
1  6.932635
1  6.804854

In [54]:
MAPE_train_df

0      MAPE
1  2.662512
1  2.680875
1  2.704113
1  2.704204
1  2.674498

In [55]:
compared['APE'].describe()

count    1291.000000
mean        0.068049
std         0.063479
min         0.000089
25%         0.025739
50%         0.053609
75%         0.096561
max         1.135550
Name: APE, dtype: float64

In [56]:
compared_train.sort_values('APE',ascending=False)

0  keiyaku_pr       APE
1469  4.691172e+06     3500000  0.340335
3722  1.351600e+07    10800000  0.251481
2885  2.930324e+07    24000000  0.220968
537   1.589137e+07    19900000  0.201439
1527  8.612864e+06     7300000  0.179844
3719  1.970623e+07    17000000  0.159190
3718  1.970623e+07    17000000  0.159190
3498  1.954090e+07    17000000  0.149465
1712  2.524942e+07    29500000  0.144087
4832  1.827815e+07    16000000  0.142385
2727  1.823766e+07    16000000  0.139854
2207  2.486795e+07    21900000  0.135523
3063  2.244546e+07    19800000  0.133609
1480  2.755255e+07    31800000  0.133567
1109  2.944428e+07    26000000  0.132472
811   9.849407e+06     8700000  0.132116
2457  1.471551e+07    13000000  0.131962
3266  2.145070e+07    18990000  0.129579
4238  1.694245e+07    15000000  0.129497
2381  4.856570e+07    43000000  0.129435
1489  1.805175e+07    16000000  0.128235
3721  2.007366e+07    23000000  0.127232
5105  1.858597e+07    16500000  0.126422
4169  1.892303e+07    16800000  0.126371
1773  2.454942e+07    21800000  0.126120
353   1.970579e+07    17500000  0.126045
1490  1.908777e+07    21800000  0.124414
4070  2.055138e+07    18300000  0.123026
2895  2.792074e+07    24880000  0.122216
909   1.978540e+07    17673049  0.119524
3731  2.141254e+07    24300000  0.118825
579   2.928087e+07    33200000  0.118046
3065  2.293924e+07    26000000  0.117721
3711  2.004704e+07    22700000  0.116871
2621  1.764393e+07    15800000  0.116704
1766  2.432395e+07    21800000  0.115777
2208  2.546602e+07    28800000  0.115763
3637  1.784061e+07    16000000  0.115038
4068  2.109979e+07    23800000  0.113454
200   2.115122e+07    19000000  0.113222
710   1.224436e+07    11000000  0.113124
1108  3.086511e+07    34800000  0.113071
3974  2.422632e+07    27300000  0.112589
627   2.091086e+07    18800000  0.112280
628   2.132691e+07    24000000  0.111379
546   1.998600e+07    17990000  0.110950
2782  2.738841e+07    30800000  0.110766
3535  2.198673e+07    19800000  0.110441
2975  2.649182e+07    23900000  0.108444
3975  2.194100e+07    19800000  0.108131
1961  2.390343e+07    26800000  0.108081
4362  1.915472e+07    17300000  0.107209
2535  3.485545e+07    31500000  0.106522
2821  2.816909e+07    31500000  0.105743
580   2.896876e+07    26200000  0.105678
674   1.923860e+07    17400000  0.105667
5094  1.968017e+07    17800000  0.105627
1700  2.320301e+07    21000000  0.104905
3080  2.165102e+07    19600000  0.104644
1087  2.265465e+07    25300000  0.104559
4598  2.208793e+07    20000000  0.104396
3756  2.507701e+07    28000000  0.104393
1117  2.097942e+07    19000000  0.104180
1836  1.545222e+07    14000000  0.103730
4190  2.294717e+07    20800000  0.103229
2891  2.941449e+07    32800000  0.103217
778   2.870797e+07    32000000  0.102876
4046  2.426306e+07    22000000  0.102866
3914  1.653938e+07    15000000  0.102625
4138  2.565069e+07    23300000  0.100888
885   2.707553e+07    24600000  0.100631
1975  2.475864e+07    22500000  0.100384
4809  3.168774e+07    28800000  0.100269
3012  2.615759e+07    23800000  0.099058
365   2.072190e+07    23000000  0.099048
54    2.423988e+07    26900000  0.098889
726   2.394921e+07    21800000  0.098588
538   1.579399e+07    17500000  0.097486
4828  1.851271e+07    20500000  0.096941
3267  2.241085e+07    24800000  0.096337
3525  2.169880e+07    19800000  0.095899
2873  1.950621e+07    17800000  0.095855
3915  1.880947e+07    20800000  0.095698
550   2.170592e+07    24000000  0.095587
1054  2.805616e+07    31000000  0.094963
816   2.900673e+07    26500000  0.094594
551   1.740384e+07    15900000  0.094581
4894  1.816356e+07    16600000  0.094191
1706  2.609962e+07    28800000  0.093763
606   2.809613e+07    31000000  0.093673
2534  3.765130e+07    41500000  0.092740
4434  1.890157e+07    17300000  0.092576
1539  2.069138e+07    22800000  0.092483
3502  1.996889e+07    22000000  0.092323
2841  3.995671e+07    43900000  0.089824
2365  2.094433e+07    23000000  0.089377
2911  2.313526e+07    25400000  0.089163

In [57]:
compared.sort_values('APE',ascending=False)

0  keiyaku_pr       APE
1109  1.174552e+07     5500000  1.135550
435   2.706696e+07    18500000  0.463079
926   1.087808e+07     7900000  0.376972
1097  2.705065e+07    19990000  0.353209
486   2.116742e+07    31600000  0.330145
963   7.886088e+06     6000000  0.314348
638   1.559145e+07    11990000  0.300371
26    2.633339e+07    20300000  0.297211
578   5.901443e+07    46300000  0.274610
1270  2.251504e+07    17800000  0.264890
342   1.764754e+07    23900000  0.261609
830   1.119948e+07     9000000  0.244387
923   2.460871e+07    19800000  0.242864
1201  2.943064e+07    23700000  0.241799
829   1.117498e+07     9000000  0.241665
999   4.832919e+07    39000000  0.239210
220   3.810880e+07    30800000  0.237299
1107  2.325689e+07    18800000  0.237069
759   2.361066e+07    30900000  0.235901
339   1.304426e+07    17000000  0.232690
28    2.370117e+07    19300000  0.228040
219   2.428991e+07    19800000  0.226763
92    2.537068e+07    32800000  0.226504
103   2.397077e+07    30900000  0.224247
117   1.500673e+07    19300000  0.222449
494   2.088864e+07    26800000  0.220573
960   2.289381e+07    18800000  0.217756
861   1.977705e+07    16400000  0.205918
274   2.929768e+07    24300000  0.205666
149   2.827356e+07    23500000  0.203130
1214  1.858147e+07    23300000  0.202512
954   2.235877e+07    28000000  0.201473
1064  2.144883e+07    26800000  0.199670
1266  2.850174e+07    23800000  0.197552
995   1.766127e+07    22000000  0.197215
1213  2.608165e+07    21800000  0.196406
329   2.961684e+07    24800000  0.194227
168   3.368269e+07    41800000  0.194194
922   2.552862e+07    21380700  0.194003
790   1.773416e+07    22000000  0.193902
1158  2.083610e+07    17500000  0.190634
337   1.379040e+07    17000000  0.188800
248   2.109331e+07    26000000  0.188719
795   3.533986e+07    43500000  0.187589
1047  2.351310e+07    19800000  0.187530
866   1.958181e+07    16500000  0.186776
240   2.456006e+07    20700000  0.186476
521   2.111599e+07    17800000  0.186292
1057  3.056759e+07    25800000  0.184790
115   2.782899e+07    23500000  0.184212
788   1.906315e+07    16100000  0.184047
631   2.604298e+07    31900000  0.183606
738   2.958596e+07    25000000  0.183439
1203  3.443103e+07    42000000  0.180214
30    2.377683e+07    29000000  0.180109
597   2.458884e+07    29980000  0.179825
414   3.655388e+07    31000000  0.179157
624   2.942078e+07    35800000  0.178190
147   2.827356e+07    24000000  0.178065
417   2.589616e+07    22000000  0.177098
1049  3.292543e+07    28000000  0.175908
1068  2.885805e+07    24550000  0.175481
685   3.465050e+07    41980000  0.174595
1272  4.618478e+07    55900000  0.173796
51    2.568822e+07    31000000  0.171348
1202  2.740725e+07    23403704  0.171064
775   2.398308e+07    20500000  0.169906
175   2.076289e+07    25000000  0.169485
42    3.496354e+07    29900000  0.169349
864   2.486486e+07    21300000  0.167364
241   1.984188e+07    17000000  0.167169
774   4.582854e+07    55000000  0.166754
381   2.917925e+07    34980000  0.165830
400   2.922719e+07    35000000  0.164937
639   2.589314e+07    31000000  0.164737
650   3.061597e+07    26300000  0.164105
1208  2.316401e+07    19900000  0.164021
620   2.129642e+07    18300000  0.163739
582   2.360813e+07    20300000  0.162962
1067  2.329253e+07    27800000  0.162139
546   1.996147e+07    23800000  0.161283
595   2.519938e+07    21700000  0.161262
349   1.493662e+07    17800000  0.160864
1029  2.333342e+07    27800000  0.160668
81    3.284293e+07    28300000  0.160527
1167  3.365140e+07    29000000  0.160393
673   2.351407e+07    28000000  0.160212
811   1.830969e+07    21800000  0.160106
365   2.671942e+07    31800000  0.159767
1147  2.434291e+07    20990000  0.159738
213   1.797386e+07    15500000  0.159604
916   1.970623e+07    17000000  0.159190
991   2.584213e+07    22300000  0.158840
388   4.000058e+07    47500000  0.157883
751   2.140558e+07    18500000  0.157059
888   2.294060e+07    27200000  0.156596
221   3.180319e+07    27500000  0.156480

In [58]:
MAPE_df.mean()

0
MAPE    6.855025
dtype: float64

In [70]:
#結果の確認
Submit_df 

id      MAPE_sum        MAPE_0        MAPE_1        MAPE_2  \
0     test_0000  9.783084e+07  1.904981e+07  2.032493e+07  1.925134e+07   
1     test_0001  1.319030e+08  2.635308e+07  2.614885e+07  2.675512e+07   
2     test_0002  1.259886e+08  2.535881e+07  2.549342e+07  2.539405e+07   
3     test_0003  1.379103e+08  2.719893e+07  2.821971e+07  2.747368e+07   
4     test_0004  1.321892e+08  2.665605e+07  2.617271e+07  2.663690e+07   
5     test_0005  1.237402e+08  2.477051e+07  2.480942e+07  2.470154e+07   
6     test_0006  1.333607e+08  2.698783e+07  2.662614e+07  2.654970e+07   
7     test_0007  1.259793e+08  2.517997e+07  2.538658e+07  2.513862e+07   
8     test_0008  1.311835e+08  2.633738e+07  2.608423e+07  2.661418e+07   
9     test_0009  1.466839e+08  2.930456e+07  2.940274e+07  2.939854e+07   
10    test_0010  1.374299e+08  2.749078e+07  2.725467e+07  2.777572e+07   
11    test_0011  1.617781e+08  3.203726e+07  3.257696e+07  3.287638e+07   
12    test_0012  1.708002e+08  3.433429e+07  3.377961e+07  3.346186e+07   
13    test_0013  1.915217e+08  3.911604e+07  3.754752e+07  3.785251e+07   
14    test_0014  1.378429e+08  2.760017e+07  2.791002e+07  2.769452e+07   
15    test_0015  1.305206e+08  2.644787e+07  2.657059e+07  2.583906e+07   
16    test_0016  9.201669e+07  1.793733e+07  1.903312e+07  1.890012e+07   
17    test_0017  9.521631e+07  1.849995e+07  1.973887e+07  1.921145e+07   
18    test_0018  8.778782e+07  1.716270e+07  1.806498e+07  1.789960e+07   
19    test_0019  9.574385e+07  1.879007e+07  1.984774e+07  1.941586e+07   
20    test_0020  9.670644e+07  1.868754e+07  2.031882e+07  1.952823e+07   
21    test_0021  9.393129e+07  1.811585e+07  1.935153e+07  1.945695e+07   
22    test_0022  9.522545e+07  1.820358e+07  1.969115e+07  1.958333e+07   
23    test_0023  8.692329e+07  1.693065e+07  1.775198e+07  1.770727e+07   
24    test_0024  9.636650e+07  1.868533e+07  1.980985e+07  1.963890e+07   
25    test_0025  9.393129e+07  1.811585e+07  1.935153e+07  1.945695e+07   
26    test_0026  9.214270e+07  1.793595e+07  1.915180e+07  1.875119e+07   
27    test_0027  9.286362e+07  1.814431e+07  1.924941e+07  1.885408e+07   
28    test_0028  9.501607e+07  1.862773e+07  1.988481e+07  1.928941e+07   
29    test_0029  9.536500e+07  1.893476e+07  1.962764e+07  1.918464e+07   
30    test_0030  9.577877e+07  1.904933e+07  1.951232e+07  1.950248e+07   
31    test_0031  9.564003e+07  1.861464e+07  1.960452e+07  1.958602e+07   
32    test_0032  9.298061e+07  1.809020e+07  1.926881e+07  1.890671e+07   
33    test_0033  9.675996e+07  1.909920e+07  2.043396e+07  1.941621e+07   
34    test_0034  9.402969e+07  1.813304e+07  1.943915e+07  1.978800e+07   
35    test_0035  1.535952e+08  3.063875e+07  3.111204e+07  3.033363e+07   
36    test_0036  1.504857e+08  2.968195e+07  3.024867e+07  3.076203e+07   
37    test_0037  1.403789e+08  2.735731e+07  2.918405e+07  2.824277e+07   
38    test_0038  1.525483e+08  3.004455e+07  3.042197e+07  3.044406e+07   
39    test_0039  1.419089e+08  2.824187e+07  2.812997e+07  2.811048e+07   
40    test_0040  1.525001e+08  3.012374e+07  3.043278e+07  3.044064e+07   
41    test_0041  1.421209e+08  2.828255e+07  2.822564e+07  2.819477e+07   
42    test_0042  1.540605e+08  3.047898e+07  3.053789e+07  3.097520e+07   
43    test_0043  1.540280e+08  3.047275e+07  3.053458e+07  3.097520e+07   
44    test_0044  1.424736e+08  2.833756e+07  2.836357e+07  2.832552e+07   
45    test_0045  1.419089e+08  2.824187e+07  2.812997e+07  2.811048e+07   
46    test_0046  1.055220e+08  2.115343e+07  2.074423e+07  2.135370e+07   
47    test_0047  1.143956e+08  2.166933e+07  2.339812e+07  2.342457e+07   
48    test_0048  1.260519e+08  2.480482e+07  2.549279e+07  2.512179e+07   
49    test_0049  1.250999e+08  2.416374e+07  2.541709e+07  2.498339e+07   
50    test_0050  1.260467e+08  2.480482e+07  2.548429e+07  2.512179e+07   
51    test_0051  8.502162e+07  1.676885e+07  1.709420e+07  1.715255e+07   
52    test_0052  1.916955e+08  3.78010

In [61]:
importance_df = pd.DataFrame([model.feature_importance(importance_type='gain'),X.columns]).T
importance_df.rename(columns={0:'importance',1:'feature_name'},inplace =True)
importance_df.set_index('feature_name',inplace=True)

In [62]:
importance_df.sort_values('importance',ascending = False)

importance
feature_name                  
koji_tatemenseki   1.43817e+18
koji_totimenseki   8.07062e+17
rosenka_hb         7.67261e+17
kijun_tatemenseki  7.58759e+17
kijun_totimenseki  3.40724e+17
tt_mseki           3.16716e+17
toho_kyori1        2.14758e+17
latitude           1.95784e+17
eki_nm1            1.95104e+17
kijun_hb            1.8379e+17
magutchi           1.78157e+17
koji_hb            1.72052e+17
city2              1.16381e+17
tt_mseki_min_hb    1.01132e+17
tc_mseki_avg_hb    9.03218e+16
tc_mseki           7.48336e+16
city1              6.83777e+16
tt_mseki_max_hb    5.65857e+16
gas                5.59327e+16
eki_kyori1         4.52761e+16
posi_nega          4.48855e+16
gk_sho_kyori       4.10032e+16
count_gas          3.94899e+16
gk_yoc_tm          3.52925e+16
count_bokachiiki   3.46298e+16
chiseki_js_hb      3.41295e+16
minmenseki         3.39484e+16
bus_hon             3.2276e+16
count_jigata       3.21449e+16
count_hiatari      3.11075e+16
count_levelplan    3.09579e+16
menseki_hi         3.02607e+16
count_部屋数          2.99798e+16
count_eki_nm1      2.96344e+16
garage             2.90833e+16
jukyo              2.79446e+16
longitude          2.67547e+16
yheki_kotei        2.66339e+16
count_hokakisei1   2.63724e+16
hiatari            2.48488e+16
count_setsudo_hi   2.38849e+16
city3              2.33214e+16
fukuin             1.91045e+16
gk_chu_kyori       1.87094e+16
count_kobetsu1     1.86841e+16
mseki_rd_hb        1.69684e+16
count_rosen_nm1    1.65053e+16
rosen_nm1          1.64575e+16
count_jukyo        1.57315e+16
count_city1        1.47041e+16
count_city2        1.36785e+16
gk_sho_tm          1.35841e+16
count_階数           1.23987e+16
setsudo_hi         1.21956e+16
kaoku_hb           1.17757e+16
kobetsu1           1.01618e+16
shu_jutaku         9.76326e+15
jigata             9.60544e+15
count_road1_hk     9.07518e+15
hy2f_date_su       8.87254e+15
toshikuiki1         8.7888e+15
mseki_dp_hb        8.20515e+15
count_road2_hk     7.93918e+15
tochiuri_su        7.01031e+15
gk_chu_tm          6.96555e+15
count_setsudo_kj    6.6658e+15
count_yoto1        6.63107e+15
setsudo_kj         6.60183e+15
sho_super          6.59562e+15
bus_kyori1          6.2467e+15
teiho1             6.19297e+15
gesui              6.15589e+15
count_hw_status    5.98182e+15
count_city3        5.58205e+15
count_kobetsu3     4.22874e+15
count_toshikuiki1  3.83627e+15
count_gesui        3.82278e+15
hy3f_date_su       3.60758e+15
count_bas_toho1    3.58974e+15
kaimono            3.41263e+15
rs_n_kdate2        3.35471e+15
bas_toho1          3.33378e+15
kborjs             3.05522e+15
chikukeikaku       2.65573e+15
rs_w_kdate2        2.52746e+15
toho_kyori2        2.50861e+15
eki_kyori2         2.49589e+15
usui               2.29116e+15
rs_s_kdate2        2.06484e+15
count_kobetsu2     2.00728e+15
road3_fi           1.97152e+15
count_hokakisei2   1.93908e+15
count_yoto2        1.78045e+15
yoto1              1.69927e+15
count_rosen_nm2     1.6376e+15
rs_e_kdate2        1.62284e+15
count_road2_sb     1.55023e+15
sho_conv           1.51078e+15
kodochiku          1.36547e+15
road1_hk           1.31926e+15
...                        ...
count_eki_nm2      9.15139e+14
levelplan          8.94541e+14
road1_sb           7.42126e+14
road2_hk           7.24663e+14
count_road3_hk     6.47663e+14
rs_n_parking       6.33962e+14
shu_kaido          6.17462e+14
count_bas_toho2    6.10259e+14
rs_e_parking       6.06383e+14
kaoku_um           5.99209e+14
rs_e_tahata        5.91575e+14
kinshijiko         5.59193e+14
kaihatsukyoka      5.51562e+14
shu_line_ari       5.33679e+14
count_kodochiku    5.08575e+14
sho_market         4.92682e+14
rs_w_m_nashi       4.76109e+14
count_hokakisei3   4.27806e+14
rs_s_m_nashi       4.26594e+14
hokakyoka          3.81552e+14
rs_s_parking       3.60178e+14
bas_toho2          3.30273e+14
rs_w_parking       3.19179e+14
fi4m_yohi          3.08678e+14
count_road1_sb     3.05005e+14
count_bastei_nm1   2.87078e+14
count_usui         2.

In [63]:
importance_df.query('importance >0').index.tolist()

['tc_mseki',
 'tt_mseki',
 'levelplan',
 'fukuin',
 'magutchi',
 'setsudo_hi',
 'setsudo_kj',
 'jigata',
 'hiatari',
 'garage',
 'kobetsu1',
 'jukyo',
 'chiseki_js_hb',
 'yoto1',
 'gesui',
 'gas',
 'usui',
 'tochiuri_su',
 'joken_su',
 'hy2f_date_su',
 'hy3f_date_su',
 'road1_hk',
 'road1_sb',
 'road2_hk',
 'road2_sb',
 'road3_sb',
 'road3_fi',
 'road4_sb',
 'kaoku_um',
 'kaoku_hb',
 'yheki_kotei',
 'yheki_umu',
 'yheki_yohi',
 'gk_sho_kyori',
 'gk_chu_kyori',
 'kborjs',
 'hw_status',
 'toshikuiki1',
 'kodochiku',
 'chikukeikaku',
 'keikakuroad',
 'kaihatsukyoka',
 't53kyoka',
 'hokakyoka',
 'bokachiiki',
 'minmenseki',
 'hokakisei1',
 'kinshijiko',
 'rosenka_hb',
 'koji_hb',
 'kijun_hb',
 'mseki_rd_hb',
 'mseki_dp_hb',
 'tt_mseki_min_hb',
 'tt_mseki_max_hb',
 'tc_mseki_avg_hb',
 'fi4m_yohi',
 'bus_yohi',
 'bus_hon',
 'sho_conv',
 'sho_super',
 'sho_shoten',
 'sho_market',
 'shu_jutaku',
 'shu_park',
 'shu_shop',
 'shu_factory',
 'shu_bochi',
 'shu_kokyo',
 'shu_kaido',
 'shu_line_ari'

In [64]:
importance_df.query('importance >0').shape

(162, 1)

In [65]:
importance_df.shape

(202, 1)

In [66]:
Submit_df

id      MAPE_sum        MAPE_0        MAPE_1        MAPE_2  \
0     test_0000  9.801211e+07  1.882709e+07  2.053789e+07  1.936538e+07   
1     test_0001  1.321413e+08  2.665431e+07  2.635524e+07  2.672689e+07   
2     test_0002  1.254867e+08  2.519976e+07  2.514737e+07  2.552844e+07   
3     test_0003  1.381256e+08  2.773684e+07  2.815998e+07  2.744669e+07   
4     test_0004  1.326665e+08  2.651164e+07  2.667575e+07  2.672998e+07   
5     test_0005  1.236494e+08  2.486503e+07  2.467316e+07  2.464332e+07   
6     test_0006  1.323382e+08  2.664905e+07  2.653315e+07  2.641947e+07   
7     test_0007  1.256053e+08  2.550824e+07  2.514386e+07  2.503928e+07   
8     test_0008  1.317335e+08  2.648538e+07  2.639080e+07  2.671028e+07   
9     test_0009  1.463569e+08  2.940064e+07  2.944411e+07  2.962938e+07   
10    test_0010  1.384379e+08  2.774941e+07  2.769854e+07  2.805109e+07   
11    test_0011  1.608149e+08  3.168782e+07  3.290398e+07  3.245835e+07   
12    test_0012  1.720068e+08  3.414359e+07  3.385701e+07  3.411554e+07   
13    test_0013  1.902039e+08  3.832682e+07  3.682772e+07  3.807077e+07   
14    test_0014  1.392036e+08  2.792619e+07  2.811466e+07  2.772830e+07   
15    test_0015  1.306450e+08  2.608079e+07  2.638406e+07  2.619149e+07   
16    test_0016  9.151546e+07  1.803732e+07  1.853274e+07  1.825176e+07   
17    test_0017  9.442903e+07  1.843734e+07  1.930781e+07  1.855836e+07   
18    test_0018  8.687716e+07  1.723705e+07  1.758199e+07  1.705057e+07   
19    test_0019  9.468677e+07  1.868417e+07  1.926861e+07  1.863246e+07   
20    test_0020  9.568135e+07  1.872833e+07  1.970286e+07  1.895218e+07   
21    test_0021  9.284241e+07  1.814149e+07  1.853264e+07  1.849552e+07   
22    test_0022  9.430018e+07  1.832577e+07  1.903738e+07  1.865106e+07   
23    test_0023  8.519570e+07  1.662663e+07  1.672054e+07  1.700424e+07   
24    test_0024  9.577985e+07  1.871098e+07  1.932550e+07  1.915076e+07   
25    test_0025  9.284241e+07  1.814149e+07  1.853264e+07  1.849552e+07   
26    test_0026  9.160900e+07  1.792712e+07  1.870067e+07  1.815552e+07   
27    test_0027  9.276527e+07  1.795842e+07  1.887516e+07  1.846962e+07   
28    test_0028  9.421482e+07  1.847541e+07  1.913724e+07  1.857335e+07   
29    test_0029  9.537479e+07  1.841262e+07  1.937509e+07  1.899361e+07   
30    test_0030  9.514346e+07  1.866053e+07  1.915237e+07  1.902105e+07   
31    test_0031  9.498449e+07  1.820935e+07  1.905669e+07  1.876982e+07   
32    test_0032  9.219097e+07  1.788241e+07  1.894670e+07  1.812738e+07   
33    test_0033  9.627508e+07  1.882237e+07  1.995455e+07  1.907335e+07   
34    test_0034  9.326003e+07  1.828186e+07  1.859001e+07  1.865664e+07   
35    test_0035  1.521576e+08  2.987905e+07  3.046974e+07  3.060402e+07   
36    test_0036  1.505786e+08  2.992551e+07  3.058563e+07  3.041053e+07   
37    test_0037  1.392735e+08  2.697001e+07  2.898851e+07  2.775221e+07   
38    test_0038  1.528643e+08  3.063273e+07  3.055814e+07  2.996985e+07   
39    test_0039  1.425844e+08  2.851015e+07  2.867054e+07  2.775935e+07   
40    test_0040  1.528414e+08  3.053394e+07  3.050991e+07  2.994361e+07   
41    test_0041  1.426547e+08  2.853286e+07  2.871332e+07  2.775798e+07   
42    test_0042  1.547680e+08  3.048853e+07  3.113347e+07  3.040496e+07   
43    test_0043  1.546666e+08  3.047046e+07  3.113345e+07  3.040496e+07   
44    test_0044  1.430617e+08  2.860964e+07  2.889338e+07  2.789550e+07   
45    test_0045  1.425844e+08  2.851015e+07  2.867054e+07  2.775935e+07   
46    test_0046  1.046093e+08  2.140110e+07  2.009235e+07  2.147730e+07   
47    test_0047  1.130998e+08  2.146958e+07  2.292973e+07  2.356080e+07   
48    test_0048  1.255203e+08  2.488844e+07  2.539183e+07  2.498085e+07   
49    test_0049  1.243629e+08  2.413151e+07  2.507817e+07  2.496707e+07   
50    test_0050  1.255907e+08  2.488844e+07  2.539183e+07  2.502658e+07   
51    test_0051  8.580830e+07  1.666875e+07  1.717204e+07  1.712104e+07   
52    test_0052  1.912768e+08  3.81281

In [67]:
Submit_df[['id','MAPE_mean']].to_csv('output/submit_0803_4.tsv',header=False,index=False,sep ='\t')

In [68]:
importance = importance_df.reset_index().rename(columns={'feature_name':'項目名'})

In [69]:
pd.merge(importance,data_definition).sort_values('importance',ascending=False)

項目名   importance データ種別           項目名（日本語）  \
60        rosenka_hb  7.67261e+17    現場           路線価格(平米)   
1           tt_mseki  3.16716e+17    号棟               建物面積   
123          eki_nm1  1.95104e+17    現場                 駅1   
62          kijun_hb   1.8379e+17    現場           基準地価(平米)   
5           magutchi  1.78157e+17    号棟              間口〔m〕   
61           koji_hb  1.72052e+17    現場           公示地価(平米)   
65   tt_mseki_min_hb  1.01132e+17    現場         建物最小面積(平米)   
67   tc_mseki_avg_hb  9.03218e+16    現場         土地平均面積(平米)   
0           tc_mseki  7.48336e+16    号棟               土地面積   
66   tt_mseki_max_hb  5.65857e+16    現場         建物最大面積(平米)   
21               gas  5.59327e+16    現場             設備(ガス)   
125       eki_kyori1  4.52761e+16    現場               駅距離1   
41      gk_sho_kyori  4.10032e+16    現場              小学校距離   
91         gk_yoc_tm  3.52925e+16    現場              幼稚園徒歩   
16     chiseki_js_hb  3.41295e+16    現場        地積 (実測)(平米）   
54        minmenseki  3.39484e+16    現場             最低敷地面積   
71           bus_hon   3.2276e+16    現場        平日１日のバス運行本数   
10            garage  2.90833e+16    号棟              車庫〔台〕   
15             jukyo  2.79446e+16    現場               住居表示   
38       yheki_kotei  2.66339e+16    現場  高低差現況宅盤と道/隣の最大高低差   
9            hiatari  2.48488e+16    号棟               日当たり   
3             fukuin  1.91045e+16    号棟              幅員〔m〕   
42      gk_chu_kyori  1.87094e+16    現場              中学校距離   
63       mseki_rd_hb  1.69684e+16    現場       道路（SB含む）(平米)   
122        rosen_nm1  1.64575e+16    現場                路線1   
92         gk_sho_tm  1.35841e+16    現場              小学校徒歩   
6         setsudo_hi  1.21956e+16    号棟               接道方位   
37          kaoku_hb  1.17757e+16    現場           家屋面積(平米)   
11          kobetsu1  1.01618e+16    号棟              個別要因①   
76        shu_jutaku  9.76326e+15    現場                住宅地   
8             jigata  9.60544e+15    号棟                 地型   
25      hy2f_date_su  8.87254e+15    現場          販売予定(2階建)   
45       toshikuiki1   8.7888e+15    現場           都市計画区域別1   
64       mseki_dp_hb  8.20515e+15    現場       ゴミ置場・公園等(平米)   
23       tochiuri_su  7.01031e+15    現場         販売種別(土地売り)   
93         gk_chu_tm  6.96555e+15    現場              中学校徒歩   
7         setsudo_kj  6.60183e+15    号棟               接道形状   
73         sho_super  6.59562e+15    現場               スーパー   
127           teiho1  6.19297e+15    現場             バス停徒歩1   
20             gesui  6.15589e+15    現場             設備(下水)   
26      hy3f_date_su  3.60758e+15    現場          販売予定(3階建)   
115      rs_n_kdate2  3.35471e+15    現場      隣接物件北戸建（2F以下）   
124        bas_toho1  3.33378e+15    現場              バス徒歩1   
43            kborjs  3.05522e+15    現場               取引形態   
48      chikukeikaku  2.65573e+15    現場               地区計画   
101      rs_w_kdate2  2.52746e+15    現場      隣接物件西戸建（2F以下）   
131       eki_kyori2  2.49589e+15    現場               駅距離2   
22              usui  2.29116e+15    現場             設備(雨水)   
108      rs_s_kdate2  2.06484e+15    現場      隣接物件南戸建（2F以下）   
33          road3_fi  1.97152e+15    現場              道路幅員3   
17             yoto1  1.69927e+15    現場              用途地域1   
94       rs_e_kdate2  1.62284e+15    現場      隣接物件東戸建（2F以下）   
72          sho_conv  1.51078e+15    現場               コンビニ   
47         kodochiku  1.36547e+15    現場               高度地区   
27          road1_hk  1.31926e+15    現場              道路方角1   
30          road2_sb  1.18031e+15    現場              道路種別2   
2          levelplan  8.94541e+14    号棟             階数・プラン   
28          road1_sb  7.42126e+14    現場              道路種別1   
29          road2_hk  7.24663e+14    現場              道路方角2   
117     rs_n_parking  6.33962e+14    現場           隣接物件北駐車場   
87         shu_kaido  6.17462e+14    現場               街道隣接   
96      rs_e_parking  6.06383e+14    現場           隣接物件東駐車場   
36          kaoku_um  5.99209e+14    現場               家屋現況   
100      rs_e_tahata  5.91575e+14    現場          